### ISSUE TITLE
Fix the demo projects

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1006]
In pull #1004 a bunch of demo projects were created without the
corresponding files.

Please ensure that the demo database is self-consistent: if an
active/published project exists it should have a directory in
demo-files/media or demo-files/static.  If the compressed_storage_size
is nonzero then the zip file should exist.  And so on.

Don't include any large files if they aren't needed for testing, and
don't include zip files if they aren't needed.  But make sure the demo
database follows a structure that could actually have been created.

Also, please do not create a project called "test".

**Comment by elfeto** [comment]
>Also, please do not create a project called "test".

I don't see a reason to not have a test project just for testing since this is demo dummy data for testings.
I will rollback the fixture and add the files to the PR #976

**Comment by tompollard** [comment]
@elfeto I think it's best to avoid rolling back if possible. It creates a messy/confusing commit history. Can  these issues not be addressed in a separate PR?

**Comment by bemoody** [comment]
> I don't see a reason to not have a test project just for testing since this
> is demo dummy data for testings.

Obviously they are all for testing.  But "test" is not a name that we
would ever use for a real project; among other reasons, because it's a
confusing name!  If I see a directory called "test" I assume it's not
important, if I'm creating a temporary project to test some new
feature then I might call it "test", "test" is the name of a temporary
directory that's created by the "test" management command... on and
on.  It's not a good name for something persistent!

All the existing demo projects have names beginning with "demo".
That's a good convention, please stick with it.

**Comment by elfeto** [comment]
What you mean is mostly the use of the word test as the slug that creates the persistent file.
I renamed it keeping the same naming convention we got.
I also purged the word test replacing it for demo, and added the folders/files
