### ISSUE TITLE
Parse CITI verification links

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1024]
When applying for credentialing, the applicant is asked to upload a PDF file documenting that they've taken a course in human subject research.

Valid training report files contain a link like this:

https://www.citiprogram.org/verify/?kaaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa-11111111

Training *certificate* files contain a link like this:

https://www.citiprogram.org/verify/?waaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa-11111111

(We don't accept the certificate for credentialing as it doesn't include enough detailed information.  This is a frequent source of confusion.)

These links point to a copy of the PDF file that anyone can download.  So as far as checking someone's training status is concerned, there's no need to look at the PDF file they uploaded, unless the verification service goes away for some reason.

For reviewing the application, the website could simply provide a link to citiprogram.org, avoiding the need for an extra step to check the report is authentic, and also avoiding many of the security problems of loading an untrusted PDF file from a trusted origin.

For the applicant, it would be good to have the form automatically rejected if they upload a "certificate" file.

It should be easy to do this since as far as I've seen, the original file is always PDF version 1.4 (hence, the URL is in plain text.)

**Comment by tompollard** [comment]
The suggestion of parsing the CITI link is something that has been discussed in the past, so I'm surprised to see that this isn't captured in an existing issue. Seems like a good idea.
