### ISSUE TITLE
Handmade logs are lost in a file

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#1025]
At the moments the logs sent by the logger.LEVEL are lost in a file. It would be ideal to store those in a database and attach them to a user or project to have a history that can be found easier than looking through X log files and parsing them.

**Comment by bemoody** [comment]
Can you give an example?  "Logging" covers a lot of territory.  I'm
not sure if your complaint is that the logs aren't capturing enough
information, or that they're temporary, or that it takes a long time
to read them, or what.

**Comment by elfeto** [comment]
When I said the logger.level was referring to all the log messages made by us.
E.g.
 - LOGGER.info("DOI ({0}) for project '{1}' created: {2}.".format(event, title, doi))
 - LOGGER.info('Submitting author {0} for project {1} is approving on behalf of {2}'.format(user, project, author.user))
and any other logger message written by us.

I want an easy straight forward way to access, read, use, etc...

**Comment by elfeto** [comment]
Also I think we log too little, and we can add more loggers like for the last modified etc... but that is another issue.

**Comment by tompollard** [comment]
I like the general idea of logging to a database, rather than to a file. Overall, it feels like information stored in a database is more findable and accessible, making it easier for us to analyze it.
