### ISSUE TITLE
mailto function breaks with special characters and comma

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#1028]
If the reference name of a credential application contains both a special character and a comma, the mailto function for external mail clients breaks the email.

Works fine:
 - a.reference_name = 'Saldaña Ramon'
 - a.reference_name = 'Ramon Saldana PHD'

Creates an empty 'To' mail at each comma:
 - a.reference_name = 'Ramon Saldaña, PHD'
 - a.reference_name = 'Saldaña Ramon, PHD'
 - a.reference_name = 'Saldaña, Ramon, PHD'

 
<img width="656" alt="Screen Shot 2020-04-23 at 9 18 18 AM" src="https://user-images.githubusercontent.com/3857286/80109793-8e01b100-8543-11ea-87dc-79667718c945.png">
<img width="652" alt="Screen Shot 2020-04-23 at 9 18 49 AM" src="https://user-images.githubusercontent.com/3857286/80109802-90640b00-8543-11ea-81e6-ac11e9ac71af.png">

**Comment by elfeto** [comment]
At the moment this only happens using Thunderbird, but not the OSX mail client.

**Comment by bemoody** [comment]
For clarity, could you give an example of the mailto link that it generates?

When you say "both a special character and a comma", do you mean that
it works correctly if the name contains a comma but no special
characters?  Your example of 'Ramon Saldana PHD' doesn't have a comma
in it.

**Comment by elfeto** [comment]
```
a.reference_name = 'Saldaña Ramon'
mailto:%3D%3Futf-8%3Fq%3FSalda%3DC3%3DB1a_Ramon%3F%3D%20%3Cadmin2@mit.edu%3E?

a.reference_name = 'Ramon, Saldana, PHD'
mailto:%22Ramon%2C%20Saldana%2C%20PHD%22%20%3Cadmin2@mit.edu%3E?
```
```
a.reference_name = 'Ramon Saldaña, PHD'
mailto:%3D%3Futf-8%3Fq%3FRamon_Salda%3DC3%3DB1a%3D2C_PHD%3F%3D%20%3Cadmin2@mit.edu%3E?

a.reference_name = 'Saldaña Ramon, PHD'
mailto:%3D%3Futf-8%3Fq%3FSalda%3DC3%3DB1a_Ramon%3D2C_PHD%3F%3D%20%3Cadmin2@mit.edu%3E?

a.reference_name = 'Saldaña, Ramon, PHD'
mailto:%3D%3Futf-8%3Fq%3FSalda%3DC3%3DB1a%3D2C_Ramon%3D2C_PHD%3F%3D%20%3Cadmin2@mit.edu%3E?
```

I removed the subject onwards because for this thats junk info.

The first 2 examples works fine.
It works correctly if either a comma or a special character is there, but not both at the same time.

**Comment by bemoody** [comment]
```
%3D%3Futf-8%3Fq%3FSalda%3DC3%3DB1a_Ramon%3F%3D%20%3Cadmin2@mit.edu%3E

 =?utf-8?q?Salda=C3=B1a_Ramon?= <admin2@mit.edu>?

%22Ramon%2C%20Saldana%2C%20PHD%22%20%3Cadmin2@mit.edu%3E

 "Ramon, Saldana, PHD" <admin2@mit.edu>

%3D%3Futf-8%3Fq%3FRamon_Salda%3DC3%3DB1a%3D2C_PHD%3F%3D%20%3Cadmin2@mit.edu%3E

 =?utf-8?q?Ramon_Salda=C3=B1a=2C_PHD?= <admin2@mit.edu>
```

On the one hand, it feels like a bug for Thunderbird to try to perform RFC x822 parsing of recipients *after* RFC 2047 decoding, but hey.  We're breaking RFCs anyway!

I suspect that it would work if we inserted quote characters pre-RFC-2047 (`=?utf-8?q?=22Ramon_Salda=C3=B1a=2C_PHD=22?=`).  email.utils.formataddr doesn't want to do that, though.

Of course, we could always take the easy route and just strip out commas. :P
