### ISSUE TITLE
Incorrect link to plain language summary in open data license page

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#1031]
The MIMIC-III demo uses the Open Data Commons Open Database License v1.0

https://physionet.org/content/mimiciii-demo/view-license/1.4/

The plain language summary link is incorrect:

* Incorrect link (current): http://www.opendatacommons.org/licenses/odbl/1-0/summary/
* Correct link: https://www.opendatacommons.org/licenses/odbl/summary/

**Comment by tompollard** [comment]
thanks for picking this up. @Lucas-Mc please could you take a look at fixing this?

the whole license, dua thing needs sorting out properly...
