### ISSUE TITLE
typo in method call (`submitting_author.set_display_infprevious_versiono()`)

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1034]
Not seen anything bad happening as a result, but something strange is going on here:

https://github.com/MIT-LCP/physionet-build/blob/df26605229364590870f230bf7301e82242bf004/physionet-django/project/models.py#L590

**Comment by elfeto** [comment]
As far I can tell that should be "submitting_author.set_display_info()" and I don't know where the "previous_version" came from.

No error has been raise up to now, because there is no case where separate_submitting is true yet.

**Comment by Lucas-Mc** [comment]
It appears like it came from here: ba021cf36d83417887ed26ed7c8bbfe223ba3ff8.
