### ISSUE TITLE
Purge unactivated associated emails

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#1038]
On continuation from #795 that deletes accounts that have not been activated, the same should be done for emails.

We should delete all emails that are associated to an active account, but the email has not been activated in 7 days.

Should an email notification be sent to the account primary email saying that the email has been removed since it has not been activated?

**Comment by tompollard** [comment]
Good idea.

> Should an email notification be sent to the account primary email saying that the email has been removed since it has not been activated?

Hmm, my experience of other systems is that they do not do this, so my initial thought is no. 

I think it is enough to make it clear in the activation email that the email address will be removed if it is not activated in x days.

**Comment by elfeto** [comment]
I added the email message in #1046
