### ISSUE TITLE
DOIExistsError when accepting submitted project for copyedit

### ISSUE THREAD

**Issue by Lucas-Mc** [MIT-LCP/physionet-build#1055]
When attempting to accept one of the submitted projects during the resubmission phase to move forward to the copyedit phase, I encountered a 500 server error. The error occurred when I filled out the form with "Yes" entered for every field, added some comments, selected "Accept" at the final dropdown, and pressed submit. I tried twice and it appears that the form didn't go through before throwing the error. 

Here is the traceback:
```
Traceback:

File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
 34.             response = get_response(request)

File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
 115.                 response = self.process_exception_by_middleware(e, request)

File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
 113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
 21.                 return view_func(request, *args, **kwargs)

File "./console/views.py" in handling_view
 83.                 return base_view(request, *args, **kwargs)

File "./console/views.py" in edit_submission
 278.             edit_log = edit_submission_form.save()

File "./console/forms.py" in save
 191.                         register_doi(payload, project)

File "./console/utility.py" in register_doi
 401.         raise DOIExistsError('Project already has a DOI')

Exception Type: DOIExistsError at /console/submitted-projects/bbxW97hbLqCyJ84eOFHe/edit/
Exception Value: Project already has a DOI
```

Seems related to #953 and more specifically [this](https://github.com/MIT-LCP/physionet-build/pull/953#issuecomment-603287214) comment.

**Comment by tompollard** [comment]
Thanks for making a note of this. In case the issue comes again, a brief summary of the problem is listed below:

- the `project.doi` and `project.core_project.doi` fields were both empty strings. `physionet-django/console/utility.py/register_doi()` treats an empty string as a (very short!) DOI, so it raises the DOIExistsError.
- all projects submitted since around march 2020 should assign None to the DOI fields, rather than an empty string, so the core issue should be resolved.

There may be a few existing projects in the system (like this one) that still have the empty string, so in case we encounter the error again the fix is documented below:

```
from project.models import ActiveProject
title="the project title"
x = ActiveProject.objects.get(title=title)
```

```
# check the DOI fields
x.doi
>>> ''
x.core_project.doi
>>> ''
```

```
# replace empty strings with None
x.doi = None
x.save()
x.core_project.doi = None
x.core_project.save()
```

**Comment by tompollard** [comment]
I think new projects are still being assigned an empty string for the DOI, rather than None, so this issue should be addressed either (1) by fixing the default DOI field to None for new projects or (2) updating register_doi to treat an empty string in the same way as it treats None.

**Comment by bemoody** [comment]
I haven't followed this, but that sounds right :)

We have test cases in 'project' for creating new projects, and we have
test cases in 'console' for publishing existing projects, but I don't
think we have any test case that follows the entire process from
project creation to publication to opening a new version to publishing
the new version.  It'd probably be good to write such a test case.

**Comment by tompollard** [comment]
After more testing, the core issue \*does\* appear to be resolved after all. When running locally, I've confirmed that new projects are assigned None values. 

There have also been new projects submitted on the live server (e.g. https://physionet.org/content/mimic2-iaccd/) that have been processed without any issue. 

If the error comes up again (which it might do for old projects in the system), then these can be dealt with manually.
