### ISSUE TITLE
Ordering issue with "Approve on behalf of co-authors" step

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1073]
We received following note from a submitting author of a project that was at the "Awaiting author approval" step:

> As I was accepting on behalf of two of my collaborators, there was a small glitch in the programming of the approval buttons. I started to approve from bottom to top. But when clicking the lowest button it approved the upper one (using Google Chrome). 

This sounds like a similar issue to https://github.com/MIT-LCP/physionet-build/issues/590.

**Comment by bemoody** [comment]
I don't see anything obviously wrong with the Python.

But I do notice that in awaiting_authors_table.html, it looks like
it's creating a lot of buttons and divs with the *same* id, meaning
that when you click the "approve" button, it might not activate the
correct "dialog".

(We might be able to catch bugs like this by running an HTML validator
as part of the test suite.)

It might in any case be worth clarifying the text to say "If you are
satisfied with the final state of the project, you may approve the
publication on behalf of {{author.name}}".

**Comment by SichengH** [comment]
I have recreated the bug, after many tries. Here is the tricky part, whenever you have two or more, authors that are not submitting authors are waiting for approval.  No matter which button you click, the pop-up window will show up and ask you to approve the first author. This works (1), when there is only one author needed to be approved (2) when you are approving authors in an orderly manner.
