### ISSUE TITLE
Upgrading to Django 3

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1095]
Django 3 was released at the end of 2019 (https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/). 

> "With the release of Django 3.0, Django 2.2 has reached the end of mainstream support. The final minor bug fix release (which is also a security release), 2.2.8, was issued today. Django 2.2 is an LTS release and will receive security and data loss fixes until April 2022. All users are encouraged to upgrade before then to continue receiving fixes for security issues."

We should look into upgrading at some point this year.

**Comment by kshalot** [comment]
We did a very small spike to see what the upgrade from 2.2 to 3.2 would break in physionet. Here are the findings:

#### General
- [x] `django_background_tasks` needs to be bumped. [Their documentation](https://django-background-tasks.readthedocs.io/en/latest/#supported-versions-and-compatibility) mentions 2.2 as the highest supported version. [The newer tags](https://github.com/arteria/django-background-tasks/commit/97b0a98823ef560837c6cab8e50d1530c2bcf572) in GH (published to pypi as well) mentioned added support for Django 3.0 though. Might be okay, but Django doesn't always stick to semantic versioning so 3.1/3.2 might have contained some breaking changes.
- [x] `django-debug-toolbar` needs to be bumped, `^2.0.0` should suffice
- [ ] 4 unit tests fail on `reverse` for urls that contain uidb64.
- [ ] Some easy deprecation warnings, e.g. `NullBooleanField` => `BooleanField(null=True)`

#### Minor
- [x] `from background_task.models_completed import CompletedTask` was removed in newer versions of `django_background_tasks` - change to `from background_task.models import CompletedTask`
`from django.contrib.staticfiles.templatetags.staticfiles import static` => `from django.templatetags.static import static`

**Comment by tompollard** [comment]
Now running Django 3!
