### ISSUE TITLE
Empty values for decision date for unsuccessful credentialed applications

### ISSUE THREAD

**Issue by Lucas-Mc** [MIT-LCP/physionet-build#1108]
This issue can be found on [this](https://physionet.org/console/past-credential-applications/unsuccessful) link where all applications are sorted by decision date, newest to oldest. Some of the applications have an empty value set to their decision date which is being pushed to the top of the sorted page. It appears that a `None` value may be the cause of this error but further investigation needs to be done to find the best way to fix it. https://github.com/MIT-LCP/physionet-build/blob/b1d24a04d7ad08ebe5d7217c4ab6bc2e2d201ea0/physionet-django/console/views.py#L1142-L1162

**Comment by bemoody** [comment]
Could be "remove_credentialing", see console/views.py lines 1142-1146.

We shouldn't lose this information, we should be keeping track of the
date when the original application was approved and when it was
subsequently revoked (assuming that's what happened.)

Arguably CredentialApplication is the wrong place to put this anyway,
but it'd also be confusing to have a User with is_credentialed=False
and their most recent CredentialApplication says they're approved.
