### ISSUE TITLE
Breakage due to unattended postgresql upgrade

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1135]
Over the weekend, Debian 10.6 was released, which included the upgrade from postgresql 11+200+deb10u3 to 11+200+deb10u4.  The upgrade was installed automatically, forcing the database server to restart and briefly bringing the entire site down.

Not that this is a *huge* problem, but it is an annoyance, and makes me think we should be more cautious about upgrades:

- perhaps avoid upgrading postgresql* via unattended-upgrades

- perhaps avoid installing non-security upgrades via unattended-upgrades

- perhaps run unattended-upgrades during the week, when somebody is around to notice and fix any problems immediately

- switch off Unattended-Upgrade::MailOnlyOnError so it will always send a report by mail

**Comment by bemoody** [comment]
(a) and (d) done.

**Comment by tompollard** [comment]
thanks!
