### ISSUE TITLE
Clarification to Editorial Guidelines (for References and IRB statement)

### ISSUE THREAD

**Issue by li-lcp** [MIT-LCP/physionet-build#1143]
Should we explicitly say in the PhysioNet editorial guidelines that:
(1) all references must be listed in the order in which they are cited, and 
(2) all references must be explicitly cited in order to be included? (In other words, we do not support bibliography that contains references that are not explicitly cited.)  Thanks to Tom for bringing this up.

Also, should we move the instruction about "IRB statement" from Data Description section to Methods section?

**Comment by tompollard** [comment]
Thanks Li-wei, both points sound good to me. Do you have specific suggestions about where on the website the changes should be made, along with exact wording if possible?

**Comment by li-lcp** [comment]
Sure, for the "IRB statement", here is my recommendation. Please feel free to modify:

Move the following 3 bullet points from "Content Description" section to "Methods & Technical Implementation Section"

- Data collected from human subjects: Please provide a statement that the study protocol was approved by relevant Institutional Review Boards (IRBs) or ethics committees. If human participants gave written informed consent, then please state this.
- Clinical trial data: Please specify trial registration number and registry name.
- Data collected from animals: Please specify the animal care guidelines used in collecting your data. See, for example, this project and this official NIH manual.


As to the references, we already have some wording in the guideline that references should be listed in numerical order, so probably no need to modify that particular part.   I am not 100% sure if we should have a rule that "All references must be explicitly cited in order to be included."  If anyone feels strongly about including it in the editorial guideline, then I am OK with adding that in the References section.

**Comment by li-lcp** [comment]
For the "References" section, I recommend that we add the following wording in the beginning of the paragraph:

"References: All references should be listed in the order in which they are cited."
