### ISSUE TITLE
Allow parentheses in first_name field on the user model

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1162]
Currently parentheses (`(` and `)`) are not valid characters in the `first_names` field in the user model, I assume because the characters are not supported by the following pattern:

https://github.com/MIT-LCP/physionet-build/blob/5652412b985c886db39c433f9082522a1bca9005/physionet-django/user/validators.py#L58-L64

This led to a user who registered with a given name but who goes by a different name having issues with getting credentialed. The user's preference was to list their given name along with a used name in parentheses `Given (Used)` but our validator prevented this. 

Are there any reasons why we shouldn't support parentheses in the first_name field? 

I don't think that parentheses will cause any downstream issues (e.g. when generating citations for papers, when distributing the name in structured metadata), though we should at least briefly check.

The alternative is that we add a "Please call me this" field (e.g. "Nickname", "Preferred name" etc).

**Comment by Lucas-Mc** [comment]
I think we should just add the new field since seeing something like "Pollard, Tom (Tommy), Nature 2019" would be so wrong

EDIT: I now realize Tom was a bad example name haha

**Comment by tompollard** [comment]
This is a good point Lucas! Perhaps the validation rule isn't such a bad thing after all, and I'm on the fence about whether we need/want the nickname field. I'll close this for now and we can revisit later if necessary.
