### ISSUE TITLE
Sync staging database with live database

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1186]
I don't think there is an existing issue for this, but I may have missed it. 

As noted at https://github.com/MIT-LCP/physionet-build/pull/1026, it would be good to be able to be able test changes on the staging server using a reasonably up to date version of the live database.

We should set up a process for syncing the staging database with the live version (e.g. by running a weekly cron task). Do any changes need to be made to the staging version (e.g. removing external email addresses to avoid spamming users during testing)?

**Comment by Lucas-Mc** [comment]
Done here #1196
