### ISSUE TITLE
Credential Processing Form Validation Rules

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1217]
These are my first pass guess at what the validation for the various forms should be.
Also, one should be able to reject without selecting certain options, but a comment should be required.

Key:
[x] MUST be yes
[ ] Could be no or undetermined, but still pass the stage

Initial Review
-----------
[x] Are all of the required fields complete? 
[x] Does the application clearly avoid frivolous text such as "aa"? 
[x] Is any non-English text (e.g. job titles) easily translated?

Training Check
-----------
[x] Is the CITI Completion Report attached? 
[x] Is the report up to date (i.e. not expired)? 
[x] Are all of the required modules complete? 
[x] Has the "Research and HIPAA Privacy Protections" module been completed? 
[x] Does the name on the training form match the name listed in the user profile?

ID Check
-----------
[ ] Do you find search results for the applicant's name (possibly include their organization in the search query)? 
[ ] Can you find publications linked to the applicant (possibly include the reference in the search query)? 
[x] Is the research summary sufficiently descriptive? 
[ ] If applicable, does the research summary include course name and number? 
[x] Does the research summary indicate an understanding that data must not be shared (e.g. no plural pronouns such as "we", "us", etc.)? 
[ ] Does the organization have a website or other online presence (*not* "MIT Affiliates")? 
[ ] Is the information consistent (independent researcher should not list and organization, obvious students should be listed as either "student" or "postdoc", MD's with a hospital as their organization should be "hospital researcher", the county and state mismatches, etc.)?

Reference Check
----
[x] Is the reference appropriate? 
[x] Is the reference easily searchable? 
[ ] Can you find publications linked to the reference? 
[ ] If applicable (for students and postdocs only), is the reference in a supervisory position? 
[ ] If applicable (for students and postdocs only), is the applicant included in a list of course participants?

Reference Response
----
[x] Does the reference know the applicant? 
[x] Does the reference approve the applicant for use of restricted data? 
[x] Does the response indicate an understanding that data must not be shared (e.g. no plural pronouns such as "we", "us", etc.)?

Final Review
----
[ ] Comments (required for rejected applications). This will be sent to the applicant. 
[x] Decision

**Comment by Lucas-Mc** [comment]
I think that this one should be required since any organization should have an online presence if it's valid:
```
Does the organization have a website or other online presence (not "MIT Affiliates")?
```
This one too since the information should be consistent unless we aren't being as strict as the current process?:
```
Is the information consistent (independent researcher should not list and organization,
obvious students should be listed as either "student" or "postdoc", MD's with a hospital
as their organization should be "hospital researcher", the county and state mismatches, etc.)?
```

**Comment by kepaik** [comment]
Those are fair to include.  I guess my thinking was that if the applicant doesn't, then the included reference might qualify.
