### ISSUE TITLE
Would be good to suggest/require reference emails to have an academic/corporate domain

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1225]
Some instances of "@gmail" or yahoo emails for advisors. Even if a staff page is visible on the institutional website with an email address.

Either simply by prompting when filling the application or allowing template response requesting.
Or allow a reviewer to change the addressable email address to the public one, in order to better validate their identity.

**Comment by Lucas-Mc** [comment]
This was almost done in #1193 but we needed to think about it more. Here would be a good place to start!

**Comment by kepaik** [comment]
Unfortunately, due to great firewall, we won't be able to require it completely.
But it would be good to have it a canned response for when we do recognize the institution, especially if we can find the reference's professional/institutional email online.

**Comment by tompollard** [comment]
This was implemented in https://github.com/MIT-LCP/physionet-build/pull/1807. Let's see how it goes.
