### ISSUE TITLE
View reviewer entries/comments on the "Unsuccessful Applications" page

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1232]
Maybe only once clicking "view details".

**Comment by Lucas-Mc** [comment]
There is already a column for the comments on that page unless you mean something else?

**Comment by kepaik** [comment]
I don't remember what I was talking about here.
It might have been the "Successful Applications" tab, but even then the comments are already viewable on "View Details".
Let me think if I can remember what I meant, otherwise, I'll close the issue.
