### ISSUE TITLE
Shippable Ending May 3, 2021

### ISSUE THREAD

**Issue by Lucas-Mc** [MIT-LCP/physionet-build#1258]
It looks like Shippable is ending their services effective March 3rd, 2021.... How should we handle the transition?

Here's some more info:
https://blog.shippable.com/the-next-step-in-the-evolution-of-shippable-jfrog-pipelines

**Comment by tompollard** [comment]
I think GitHub Actions does what we need. 

https://lab.github.com/githubtraining/github-actions:-continuous-integration

https://docs.github.com/en/actions/learn-github-actions

It looks like there is a Django Continuous Integration template that might be helpful for getting started: https://github.com/actions/starter-workflows/blob/c59b62dee0eae1f9f368b7011cf05c2fc42cf084/ci/django.yml
