### ISSUE TITLE
Auto-save project creation forms to avoid data being lost  

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1279]
When contributors are creating projects, they are required to populate a series of forms. The data is only saved when the "Save" button is clicked. Some of these forms are long (e.g. https://physionet.org/projects/<SLUG>/content/). 

It can waste a lot of time and effort if something happens to someone (e.g. @alistairewj) if he or she user unintentionally leaves the page before saving.

We should address this issue, perhaps by doing one or more of the following things:

- saving drafts of the text
- warning the user before they leave the page if there is unsaved content
- ...any other ideas?

**Comment by bemoody** [comment]
> It can waste a lot of time and effort if something happens to someone
> (e.g. @alistairewj) if he or she user unintentionally leaves the page
> before saving.

Sounds like there's a story there... sorry, Alistair!

If I recall correctly, CKEditor does have a way to save automatically
or to put a "save" button on the toolbar so you can save without
submitting the whole form / reloading the page.  Of course we would
need something to handle that on the backend.

I am slightly disinclined to save automatically since we don't keep any
history of edits.

Definitely using the browser's "warn before navigating away if there
are unsaved changes" would be a good idea.

**Comment by alistairewj** [comment]
> Definitely using the browser's "warn before navigating away if there
are unsaved changes" would be a good idea.

Yeah, this would have prevented my loss of data and sounds like a good change. A misplaced finger resulted in a three-finger swipe becoming a two-finger swipe, which triggered the back button, and never has there been a tale of more woe... well, maybe there's one.

**Comment by tompollard** [comment]
I've been playing around with the autosave package for ckeditor and it works well. It handles the versioning issue really nicely:

1. the page autosaves every ~20 seconds
2. if you navigate away from the page without saving, then when you return you are shown a message to say that the most recent text was not saved

![Screen Shot 2021-03-03 at 14 47 17](https://user-images.githubusercontent.com/822601/109866536-5ff4ff00-7c33-11eb-8895-a96d37dce546.png)

3. You can then check and accept/reject a diff of the changes.

![Screen Shot 2021-03-03 at 14 52 20](https://user-images.githubusercontent.com/822601/109866595-7307cf00-7c33-11eb-8d87-e932f728ef3d.png)
