### ISSUE TITLE
"Reset password" link does not consider secondary email addresses

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1291]
Users can ask to reset their password from https://physionet.org/reset-password/. This form will only send an email to primary email addresses. This is confusing for users who try to reset their password using a non-primary email address (i.e. they do not receive a password reset email, and they are unable to register because the registration form rejects the email address).

**Comment by bemoody** [comment]
True, this is a messy system.  You also cannot *log in* using any but
your primary address.  I also worry about people having old email
addresses registered that no longer belong to them.

**Comment by tompollard** [comment]
> You also cannot *log in* using any but your primary address.

Yeah :/ Didn't want to open too many cans at once, but I guess these issues do need to be considered together.

**Comment by tompollard** [comment]
@bemoody this issue has come up again. Someone had lost access to a primary address and wanted to reset their password using a secondary address. Are you okay with updating the system so that password reset emails are sent to both primary and secondary addresses?

**Comment by tompollard** [comment]
@bemoody As you say, expanding the ResetPassword form to consider secondary addresses adds risk. As a compromise, https://github.com/MIT-LCP/physionet-build/pull/2130 notifies the user of their primary address if appropriate.

> You also cannot *log in* using any but your primary address.

This issue is at least partially addressed by https://github.com/MIT-LCP/physionet-build/pull/2130. If you are unable to login and then try resetting your password, you find out why.
