### ISSUE TITLE
Autosave not cleared when form is saved

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1312]
The autosave plugin will try to automatically save the text you've entered in localStorage.  However, it doesn't delete the auto-saved text when the form is submitted.

Examples of how this can be a problem:

- Go to /projects/create/, enter an abstract, and submit the form; the new project is created.  Go to /projects/create/ to create another project.  Now the form field is blank, so it gives a warning.

- Go to /projects/SHuKI1APLrwWCqxSQnSk/content/ and click the table button to create a table.  Drag the handle at the bottom of the table to make it taller.  Submit the form.  In the autosaved text (and even in the HTTP response), the table has a "height" attribute, but ckeditor strips this attribute out so it doesn't match, and it gives you a warning.

- For various reasons it is desirable to make automated changes to the HTML content which will cause the text to differ from what was submitted.

One possibility would be to set the "saveDetectionSelectors" config property, e.g. if you set that property to "button[name='edit_description']" then the plugin will clear its local storage when a button with that name is clicked.  This isn't ideal, since clicking the button doesn't mean the data was received or saved by the server.  Better would be to somehow clear the storage in the response *after* the form is saved.

**Comment by tompollard** [comment]
@bemoody thanks for picking this up. Odd, I did some testing where I thought I saw the autosaved data in the browser being deleted when I clicked submit. I'll try to look into this.
