### ISSUE TITLE
Displaying "Pending project approval" in the outstanding tasks panel at /projects/

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1364]
If a project is pending approval by an author, it is appears in the "Pending project approval" panel on the /projects page:

![Screen Shot 2021-07-02 at 10 30 17](https://user-images.githubusercontent.com/822601/124291347-7bf5a800-db22-11eb-84ab-95fa3064a21e.png)

Submitting authors have the ability to approve the project on behalf of all authors. However, if they approve the project for themselves (but not their co-authors), the project drops out of the pending-approval panel.

I think it would make sense to update our logic so that projects that are pending approval are displayed in the submitting authors panel until all authors have approved. This gives the submitting author the opportunity to approve on their colleagues behalf if necessary.

**Comment by SichengH** [comment]
Looks like this issue is solved.
