### ISSUE TITLE
Consider removing the ArchivedProject model

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#1368]
I'm wondering how useful the `ArchivedProject` model is. The code would be a lot simpler if the `ArchivedProject` class was just deleted because of the inheritance structure that it shares with `ActiveProject`.

Here are the theoretical listed reasons from the docstring for having this model:

```
1. A user chooses to 'delete' their ActiveProject.
2. An ActiveProject is not submitted for too long.
3. An ActiveProject is submitted and rejected.
4. An ActiveProject is submitted and times out.
```

The main use for this item is to bring back projects that were once active and now archived. But if there are no such actual cases of this happening, after having launched PhysioNet for more than 2 years now, I'd say that this model should be deleted and the workflow reconsidered.

Proposal:
- For items 2 and 4, we can increase the submission/processing deadlines to a very safe long time. After repeated warnings, the project will be fully deleted.
    - If this amount of time passes, it likely indicates that there is little interest in getting the project published in the foreseeable future. If so much time passes and they want to resubmit, things will probably have changed so much that creating a new project and updating the description fields will be necessary anyway. Keeping some archived copy is of little use to anyone. 
- For item 3, reject the project, warn the users that the project will be deleted after a very safe amount of time, and then delete it.
    - If a project is flat-out rejected, it indicates that it is very unsuitable for publication, and that it will likely never be published. Keeping some archived copy is of little use to anyone.

Justification:
- Reduce annoying inheritance structure shared with `ActiveProject`
- Remove time and energy needed to consider what's happening with archived projects and data.
- Remove future development concerns when extending the `ActiveProject` model regarding how `ArchivedProject` must also be supported.

**Comment by cx1111** [comment]
@tompollard @bemoody

**Comment by cx1111** [comment]
After discussion, I've realized that when projects are rejected, we should kept a copy of the metadata, which already justifies having this model.

**Comment by bemoody** [comment]
> After discussion, I've realized that when projects are rejected, we
> should kept a copy of the metadata, which already justifies having
> this model.

Yeah, I would agree with that.

It would, I think, be better for maintainability to have a single model
(UnpublishedProject?) with a *flag* to indicate whether the project is
currently active, rather than two separate models.

Of course that's not a trivial migration to implement and there are
other areas to improve the code that I would consider higher priority.
