### ISSUE TITLE
credentialing: sort the reference email address will be helpful

### ISSUE THREAD

**Issue by sophie53** [MIT-LCP/physionet-build#1370]
in the new credentialing system, on the initial review page, it would be helpful if we could sort by reference email address. In the situation, when a professor is the reference for many student applicants....

**Comment by tompollard** [comment]
@sophie53 thanks for the reminder. The sorting may be addressed in https://github.com/MIT-LCP/physionet-build/pull/1345 which needs a review. If not, we'll implement the change soon!

**Comment by sophie53** [comment]
> @sophie53 thanks for the reminder. The sorting may be addressed in #1345 which needs a review. If not, we'll implement the change soon!

thanks Tom. Sorry, I did not see 1345

**Comment by tompollard** [comment]
@sophie53 it's good that you bumped this in our todos...the pull request has been sitting around for a while :)

**Comment by tompollard** [comment]
addressed in https://github.com/MIT-LCP/physionet-build/pull/1345 (thanks Lucas!)
