### ISSUE TITLE
Add note to README.md on how to access a debug prompt when using Docker

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1384]
To access a debug prompt raised using `breakpoint()`:

1. run `docker container ls` to get a list of active containers
2. find the "CONTAINER_ID" for the dev_1 container
3. in a new shell, attach to the container with `docker attach CONTAINER_ID`
4. the debugger should now be available in the new shell.

Update the [README.md](https://github.com/MIT-LCP/physionet-build/blob/dev/README.md) to briefly explain this process.

**Comment by tompollard** [comment]
> ![Screen Shot 2021-08-30 at 15 46 36](https://user-images.githubusercontent.com/822601/131396224-ce7d5abf-136d-4193-86c2-337087c70151.png)

thanks @danamouk  :)

**Comment by SichengH** [comment]
@danamouk Do you want to close this issue?

**Comment by danamouk** [comment]
Yes, thanks Sicheng for adding the shortcuts to detach from the docker container.
