### ISSUE TITLE
Graphs are not generating in lightwave visualization

### ISSUE THREAD

**Issue by purushottam22** [MIT-LCP/physionet-build#1445]
I am not getting the graphs of ecg records in visualize waveform. 
I replace the data files with MIT-BIH Arrhythmia Database ( https://physionet.org/content/mitdb/1.0.0/ ).
I installed this software using pycharm virtual environment on Windows 10 64 bits. 
Running python manage.py resetdb gives ok for each case. I don't find any error.

**Comment by briangow** [comment]
@purushottam22 , could you provide more details about your setup? By default, the physionet-build repository won't populate all of the files in the databases. When clicking Visualize Waveforms at the bottom of the MIT-BIH Arrhythmia Database, the waveforms seems to be plotting just fine in Lightwave for me.

**Comment by purushottam22** [comment]
Hello @briangow , I am hosting the lightWAVE locally on my system. I saved the MIT-BIH Arrhythmia Database in my local. 
![lightwaveData](https://user-images.githubusercontent.com/48179902/144796082-e804611c-e30a-4737-9f44-6bff0ae7f500.png)

When I click, 'visualize waveform' then this page occurs.
![lightwaveGraph](https://user-images.githubusercontent.com/48179902/144796137-b2a723c5-d2b2-48d7-9c0d-b52d36b0aedd.png)

And it remains in this step. There is no dropdown box for selecting record's name appears.

**Comment by briangow** [comment]
@purushottam22 , can you confirm that you are using a RECORDS file and that it provides the path to your local waveform files.
