### ISSUE TITLE
Add ORCID to DataCite payload when registering DOIs for published projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1478]
It would be nice to formally credit dataset creators with their publication records in DataCite. Now that we link user accounts to ORCID, we can add ORCIDs to the payload sent to DataCite when registering DOIs. 

e.g.

```
    <contributors>
        <contributor contributorType="ProjectLeader">
            <contributorName>Starr, Joan</contributorName>
            <givenName>Joan</givenName>
            <familyName>Starr</familyName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org">0000-0002-7285-027X</nameIdentifier>
            <affiliation>California Digital Library</affiliation>
        </contributor>
```

It looks like the update can be made somewhere in:

https://github.com/MIT-LCP/physionet-build/blob/e0118a1d46e3d6b4abf8ea07835e8b5647f6a122/physionet-django/console/utility.py#L512-L536

See the following links for more information on the DataCite API:
- https://support.datacite.org/docs/api 
- https://support.datacite.org/docs/mds-api-guide

**Comment by tompollard** [comment]
Note to self: see: https://developers.google.com/search/docs/advanced/structured-data/dataset for a longer list of fields that we could consider adding (e.g: "isAccessibleForFree", "Keywords", etc.)

**Comment by superryeti** [comment]
solved by https://github.com/MIT-LCP/physionet-build/pull/1931
