### ISSUE TITLE
Reference reordering triggers a 500 error

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#1557]
It's possible to get a 500 Server Error by moving a reference in the list of references on the content page. Here's how I reproduced:

1. Had a project with 7 references.
2. Add a new blank reference.
3. Move the text of reference 7 to one of the other spots (I moved it to spot 1).
4. Remove the (blank) 8th reference.
5. Click save content

This consistently resulted in a 500 error (and I did it thrice on production just now, ~4:54pm). It looks like a duplicate key error:

> IntegrityError at /projects/yk9LlDASyilE4qnZ7Il8/content/
> duplicate key value violates unique constraint "project_reference_description_content_type_8b53e7b5_uniq"
DETAIL:  Key (description, content_type_id, object_id)=(Makam AN, Lanham HJ, Batchelor K, Samal L, Moran B, Howell-Stampley T, Kirk L, Cherukuri M, Santini N, Leykum LK, Halm EA. Use and satisfaction with key functions of a common commercial electronic health record: a survey of primary care providers. BMC medical informatics and decision making. 2013 Dec;13(1):1-7., 11, 881) already exists.

I don't think it's super unusual to re-order references so this is probably more common of an issue than it sounds.

**Comment by tompollard** [comment]
yeah, this is a major bug that has been sitting around for too long! it's the same issue described in https://github.com/MIT-LCP/physionet-build/issues/1105. basically the reference object doesn't include an `order` attribute, and it should do!

**Comment by tompollard** [comment]
@amitupreti iif you have time (and Alistair is okay with this) please could you take a look at this issue to see if you can come up with a fix?

I made a start on the initial part of the work, which is migrating from using primary key for sorting to an explicit order: https://github.com/MIT-LCP/physionet-build/pull/1602

Now we need to use the order in the reference tool. @Rutvikrj26 made a start, so could point you in the right direction.

**Comment by superryeti** [comment]
@tompollard  Sounds great. Thank you. 

let me add this to my task list.

**Comment by tompollard** [comment]
This should now be fixed (thanks @amitupreti!). References now have an `order` and this order is used to sort references.
