### ISSUE TITLE
Placement of Ethics section

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1588]
What is Ethics doing in between Usage Notes and Release Notes?  This just seems like a non-sequitur; either Ethics belongs near the beginning next to Data/Software/Model Description or it belongs near the end next to Conflicts of Interest.

Anyway, as this is one of the sections of the project content, it should be part of /projects/X/content/.

*grumble, grumble*

**Comment by tompollard** [comment]
Yeah, fair point, next to conflicts of interest is probably a better place!

> Anyway, as this is one of the sections of the project content, it should be part of /projects/X/content/.

Personally I prefer keeping the ethics section independent of the content section because: (1) it emphasizes the importance of project ethics (2) it gives us flexibility to allow file uploads etc.

**Comment by bemoody** [comment]
So, would it be acceptable to change the ordering?

Here are the projects that contain both ethics_statement and
release_notes.  None of them have extremely detailed release notes.  I
don't think that swapping these two sections would negatively affect
the flow of the document, and for most of these would be barely
noticeable.

https://physionet.org/content/brateca/1.0/#ethics

https://physionet.org/content/calcium-imaging-sleep-state/1.0.1/#ethics

https://physionet.org/content/circor-heart-sound/1.0.1/#ethics

https://physionet.org/content/circor-heart-sound/1.0.2/#ethics

https://physionet.org/content/circor-heart-sound/1.0.3/#ethics

https://physionet.org/content/cpap-data-canterbury/1.0.1/#ethics

https://physionet.org/content/ecg-ppg-simulator-arrhythmia/1.3.1/#ethics

https://physionet.org/content/hmc-sleep-staging/1.1/#ethics

https://physionet.org/content/icentia11k-continuous-ecg/1.0/#ethics

https://physionet.org/content/kinecal/1.0.0/#ethics

https://physionet.org/content/norwegian-athlete-ecg/1.0.0/#ethics

https://physionet.org/content/pulse-transit-time-ppg/1.0.0/#ethics

https://physionet.org/content/pulse-transit-time-ppg/1.1.0/#ethics

https://physionet.org/content/vindr-mammo/1.0.0/#ethics

https://physionet.org/content/vindr-pcxr/1.0.0/#ethics

https://physionet.org/content/wearable-exercise-frailty/1.0.0/#ethics

**Comment by tompollard** [comment]
Yeah, I think tweaking the order would be fine!

**Comment by tompollard** [comment]
@bemoody fixed in https://github.com/MIT-LCP/physionet-build/pull/1592 ?
