### ISSUE TITLE
Exception Value: 'DataAccessRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1590]
As mentioned in https://github.com/MIT-LCP/physionet-build/issues/1589, we've seen an error message when the host of a self-managed project attempts to view a data request. The traceback is below:

```
Internal Server Error: /access-requests/SLUG/VERSION/ID/

AttributeError at /access-requests/SLUG/VERSION/ID/
'DataAccessRequest' object has no attribute 'user'

Request Method: GET
Request URL: https://www.physionet.org/access-requests/SLUG/VERSION/ID/

Traceback:

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/exception.py" in inner
 34.             response = get_response(request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/base.py" in _get_response
 115.                 response = self.process_exception_by_middleware(e, request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/base.py" in _get_response
 113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
 21.                 return view_func(request, *args, **kwargs)

File "./project/views.py" in data_access_request_view
 2099.             migrated_user_id=access_request.user

Exception Type: AttributeError at /access-requests/SLUG/VERSION/ID/
Exception Value: 'DataAccessRequest' object has no attribute 'user'
Request information:
USER: XXX
```

The chunk raising the error is below:

https://github.com/MIT-LCP/physionet-build/blob/26182475ab095f3c9e937ba2dffebd1ce3165d12/physionet-django/project/views.py#L2096-L2100

**Comment by tompollard** [comment]
It looks like the problem occurs when a non-credentialed user submits a data request at:
http://localhost:8000/request-access/demoselfmanaged/1.0.0/

So we need to either:
1) require users to be credentialed before submitting a data access request.
2) update the system to handle applications from non-credentialed users.

**Comment by alistairewj** [comment]
I would vote for 1! Maybe the request access page checks if you are credentialed?

**Comment by tompollard** [comment]
Sorry, the problem was actually simpler than I'd thought...it's just that the user attribute is named `requester` on the DataAccessRequest object (not `user`). I think we can ignore the points above for now!
