### ISSUE TITLE
"is_valid" and "is_expired" flags on training objects should be mutually exclusive. Ref #1595

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1596]
There seems to be a bug in the way training reports are managed. I would expect the "is_valid" and "is_expired" flags for a Training object to be mutually exclusive:

https://github.com/MIT-LCP/physionet-build/blob/966e22f57aed1b8c06c4391f36b949c32e04d753/physionet-django/user/models.py#L1103-L1115

But it is possible for both flags to return True for a single training type:

```python
>>> a
<Training: Training object (x)>
>>> a.is_valid()
True
>>> a.is_expired()
True
```

We have users reporting that their training is shown as "active" but they are unable to access a dataset because they are required to complete training. They cannot upload new training because they already have active training, so they are stuck. See also #1595.

**Comment by tompollard** [comment]
In the case of one of the users I am checking `a.training_type.valid_duration` is empty, so `is_expired` is returning True. We do not support expiry dates for training, so what should this field contain?

**Comment by tompollard** [comment]
Also, if there is at least one user that returns "is_expired" for their training, why is the list at https://physionet.org/console/training/expired/ empty?

**Comment by tompollard** [comment]
It looks like the expired list is generated with:

https://github.com/MIT-LCP/physionet-build/blob/966e22f57aed1b8c06c4391f36b949c32e04d753/physionet-django/user/managers.py#L22-L29

This needs a bit of investigation.

**Comment by tompollard** [comment]
This template is suggesting that if a training type does not have a `training.valid_datetime` then the training is valid until the end of the 🌎

https://github.com/MIT-LCP/physionet-build/blob/7255ec760360b843abc2970853fc5fe9192fda96/physionet-django/console/templates/console/valid_training_table.html#L21-L27

**Comment by tompollard** [comment]
I think the bug is in the following chunk:

```
 def is_expired(self): 
     if self.status == TrainingStatus.ACCEPTED: 
         if not self.training_type.valid_duration: 
             return True 
         else: 
             return self.process_datetime + self.training_type.valid_duration < timezone.now() 
```

I think whoever wrote this intended `if not self.training_type.valid_duration` to return False, not True (i.e. they intended for training types without a duration to never expire).

**Comment by tompollard** [comment]
For now I have set our CITI training expiry date to 100 years in the future.

**Comment by superryeti** [comment]
Hi @tompollard , I think this should be closed. @harryface  fixed this on https://github.com/MIT-LCP/physionet-build/pull/1678

**Comment by tompollard** [comment]
I think you're right! Thanks @amitupreti (and @harryface!)
