### ISSUE TITLE
   I couldn't receive physionet's account registration email on my institutional email account

### ISSUE THREAD

**Issue by wyh196646** [MIT-LCP/physionet-build#1606]
I just sign up the physionet with my institution email account，EMAIL ,however,I can't receive the validation email,I check my spam, there was no email from Physionet. I just sign up with my personal email ,and sign up successful,but i Credentialing several times,all be rejected,the physionet require my institution email ,this is really a terriable problem ,how can i slove it?

**Comment by alistairewj** [comment]
closed (stale and user raised a ticket via #1626)
