### ISSUE TITLE
I have submit my CITI training report for four weeks,but But it has been in the state of under review,not been approved?

### ISSUE THREAD

**Issue by wyh196646** [MIT-LCP/physionet-build#1626]
I  submited my CITI training report four weeks ago,but it has been in the state of under review,not been approved?
I am sure that my traning report is correct and there is no problem,just CITI Data or Specimens Only Research and the report with my score.
How can I slove this problem,i really need to use the MIMIC dataset for my research.

**Comment by tompollard** [comment]
@wyh196646 please create a ticket at: https://physionet.freshdesk.com/support/home and someone in the credentialing team will help out.
