### ISSUE TITLE
Provide a getting started guide for new developers

### ISSUE THREAD

**Issue by sul24mib** [MIT-LCP/physionet-build#1651]
The [README.md](https://github.com/MIT-LCP/physionet-build/blob/dev/README.md) currently provides basic guidance on how to run the website locally. I think it would be helpful to provide more detailed instructions for new developers who are not familiar with tools such as: 

- Terminal commands
- Django 
- Git
- Virtual environments
- Docker 
- Python linters

I would be happy to start creating a wiki page that includes some guidance on these topics.

**Comment by tompollard** [comment]
Thanks @sul24mib, sounds good if you'd like to make a start!

**Comment by joamats** [comment]
@tompollard can we close this issue? 
(https://github.com/MIT-LCP/physionet-build/pull/1705 has been merged)

**Comment by tompollard** [comment]
Yes, I think so! We can continue to develop the readme and wiki.
