### ISSUE TITLE
Add a "past events" section to the events home page

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1664]
Currently we display a list of events at https://localhost:8000/events/ under an "Active Events" title. We should add a new section called "Past Events". In the Past Events section we should 

- Display projects where the End Date of the event is in the past.
- Perhaps hide the sign up link for past events and prevent new users from signing up (e.g. if someone clicks a link for a past event, they might see a message saying "This event has now finished".)

**Comment by Chrystinne** [comment]
@tompollard just to confirm if I get this straight: Is the link below the one we need to hide for past events?

![link to remove](https://user-images.githubusercontent.com/4949149/189998509-e3762a99-db90-4637-9f5f-04d92c02d50f.png)

If anyone has already received the link, we will replace the previous Event registration confirmation below with the "This event has now finished" message.

![enroll](https://user-images.githubusercontent.com/4949149/189998901-9194c316-eabc-4f9d-9b01-2de72fc8ec62.png)

**Comment by tompollard** [comment]
Thanks Chrystinne, yes, that's what I was thinking (though we are making this up as we go along...please suggest alternative ideas if something better springs to mind).
