### ISSUE TITLE
Credentialing Console: Add column with training status

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1679]
1. Active
2. Under Review
3. None

**Comment by Chrystinne** [comment]
@kepaik I've created the pull request below to solve this issue:

https://github.com/MIT-LCP/physionet-build/pull/1689

**Comment by Chrystinne** [comment]
@kepaik Have you thought about how the system should work (i.e., which information should be shown on the Training Status) in situations where:

1) A user has multiple CITI training applications (e.g., a "rejected" application and an application "under review");

2) A user has multiple types of training (e.g. CITI training, Datathon).

I've added the Training Status column, but I haven't considered these situations on my Pull Request (https://github.com/MIT-LCP/physionet-build/pull/1689). 

So, I came up with this possible solution: turning the two columns "Training Type" and "Training Status" into one (Training Status). So Training Status would list every training available for each user along with its status. (e.g. CITI program: Active, Datathon training: Under review). 

Would that make sense to you? Or do you have a better idea?

**Comment by kepaik** [comment]
Right now, I don't have any other types of training, so it's not useful to me for credentialing, only whether it's active or not.  I don't know if Tom or Alistair have other plans.

To clarify, this request was for the Training reports, which you've already completed, not the Credentialing processing.  For me, it's not useful there as it's not part of the processing decision tree. Might actually clutter the screen with too many options.

**Comment by Chrystinne** [comment]
@kepaik Ok. So, if there is no need for the "Training Status" column on the Credentialing table, we can close this issue, right? And I'll close the PR (https://github.com/MIT-LCP/physionet-build/pull/1689).
