### ISSUE TITLE
Static pages: "About" page cannot be edited

### ISSUE THREAD

**Issue by january-adams** [MIT-LCP/physionet-build#1707]
The "About" page under static pages cannot be edited (including to adjust the Nav order), since it calls for a URL of the form `/about/value/` and the URL is instead only `/about/`.
![staticpages_about_error](https://user-images.githubusercontent.com/84862315/202017008-9c7fc29a-645c-4e8c-9591-39c82927242e.png)

**Comment by tompollard** [comment]
Thanks @january-adams. This was fixed by @harryface in #1716.
