### ISSUE TITLE
L01: Arbitrary file upload in training

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1732]
Any file can be uploaded to validate training by changing its extension to .pdf. The file's header should be checked to ensure it matches a PDF file's signature.

Solution would probably be similar to the https://github.com/MIT-LCP/physionet-build/issues/1730  as its the same file validation task

**Comment by bemoody** [comment]
Indeed, if it's required to be a .pdf file we should check that it's actually a PDF file.

(On the other hand I think it would be better to require it to be a genuine training report from CITI, and not get into handling untrusted PDF files at all.)

**Comment by alistairewj** [comment]
One of the training courses we require is TCPCS-2, which is a simple PDF. Although CITI has an API for their certificates, the group behind TCPCS-2 are a long way from having that kind of service, so validating PDFs are actually what they say they are is helpful for us.

**Comment by bemoody** [comment]
There's validating file formats and then there's verifying/authenticating the file contents.  The latter is worth doing but worth keeping as a separate issue (#1180).
