### ISSUE TITLE
I01: Limit number of emails attached to an account / make the limit configurable

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1734]
Currently, Users are able to add a large number of associated email to their account,  On Test Cycura showed an example of adding 100 associated emails to account.

It  might make sense to limit a max number of emails that can be associated to user(maybe we can have a something in env file for this which can let each deployment decide if they want to implement the email limit.

**Comment by bemoody** [comment]
Ten should be enough for anybody, right? :P

Well, I could imagine wanting to set up a separate contact address for each project, but nobody's done that as far as I know.

**Comment by superryeti** [comment]
Default 10 makes sense to me.

Also in case if someone needs to associate a lot of emails because they have a lot of projects published, i suppose we could make it possible by using some kind of integer somewhere in the User model(so when user signs up, they would get the default email limit), and if someone needs to add more email as this is a special case, maybe the user could ask admin to increase that number for them.

But maybe it will be too much work and something we dont want to pursue.


Please let me know if you think we want to have the ability to update the max email quota for specific users. or just implement the hard email limit for all users.

**Comment by superryeti** [comment]
We decided to not make changes to model and add a simple check on the views to limit users from adding unlimited emails
