### ISSUE TITLE
M05: Project File Upload Request Can Be Replayed

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1737]
Context: The generate_signed_url view is responsible to create a google storage signed url and upload the files to google storage. it looks like the PUT request that uploads files to the signed url can be replayed to upload another file.
This can be used to bypass the manual review process

For example: let say author submits valid files, and copies the PUT request that uploaded the files. Later once the Editor has approved the project and before other author approve it, the submitting author can use that PUT request and upload another file(as the current view lets the link to be valid for 24 hours). All of this is assuming that the editor review and approves project before 24 hours.

Recommendation: The signed URL should only be usable once, or if not the link should only remain active for ~60  minutes or something like that.

Also the security report also mentions, that the file size is not verified if the user directly submits the modified PUT request to change the uploaded file.

Here is the exact line from the report(just in case i misunderstood)

         
<img width="732" alt="image" src="https://user-images.githubusercontent.com/24412619/206302142-ed4ea4bb-7d9f-4558-8888-4be4fd741d53.png">

**Comment by bemoody** [comment]
Clearly needs somebody with a deep understanding of GCS - not me.

generate_signed_url_v4 documentation is none too clear (and, uhh... are you importing that function from a non-public module?!)

One idea to deal with the "adding files after project submission" issue would be to see whether you can create an *ephemeral set of credentials* for each project.  That wouldn't help with "repeatedly uploading huge files to exceed your storage allowance", though.

**Comment by superryeti** [comment]
Discussed with Alistair
Here is the summary

1. We cant limit the upload size in GCP buckets, so we decided to just limit the signed url and make it ephemeral
2. Regarding the use of private module, replacing this with https://github.com/googleapis/python-storage/blob/HEAD/samples/snippets/storage_generate_upload_signed_url_v4.py.  we can see it being used in a test in googles python library https://github.com/googleapis/python-storage/blob/7dfeb622bb966e368786e3c9be67ad77b3150725/tests/system/test__signing.py#L38

**Comment by superryeti** [comment]
Will open 1 PR for replacing the private module and another PR for making updating the signed url expiration.

**Comment by bemoody** [comment]
I would add a few things, following our discussion this morning.

If I understood correctly what Karol was saying, the client is required to *begin uploading* the file before the signed URL expires, but the client can *continue* transmitting data after that point in time.

This would mean that expiration of the signed URL *does not guarantee* that project files can no longer be modified.

So I have three questions:

First, whether there is any limit on how long the client may take to upload data to a signed URL.

Second, whether it is possible to make the project bucket *read-only* when it is submitted (i.e., revoke write acccess for anyone who previously had access), and whether that would effectively block any in-flight uploads.

Third, if it is *not* possible to block in-flight uploads and there is *no* predictable time limit on how long an upload may take, whether it is possible, using the GCS client API, to find out whether there are any uploads currently in flight.

These are questions that (from what I've seen of Google's documentation) are probably not documented anywhere, and require an *actual engineer at Google* to give an authoritative answer.

**Comment by superryeti** [comment]
resolved by https://github.com/MIT-LCP/physionet-build/pull/1840
