### ISSUE TITLE
Hide LightWave for projects under embargo?

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1770]
@briangow I notice that we display a "Visualize waveforms" link next to the entry for https://physionet.org/content/mimic-iv-ecg/ on the front page of PhysioNet. When I click the link, I am taken to LightWave at: https://physionet.org/lightwave/?db=mimic-iv-ecg/0.1. 

LightWave then gets stuck at: "Reading list of records". Presumably this is because LightWave is unable to read the records because of the embargo. I think we should probably hide LightWave for people in this case?

**Comment by briangow** [comment]
@tompollard , good catch! I didn't realize we displayed a Visualize Waveforms link by default on the front page if a project has waveforms.

**Comment by briangow** [comment]
@tompollard , I just submitted a PR to remedy this in the case of embargo. However, I'd assume we'd see similar behavior in Lightwave for any project that isn't open access since access isn't granted until the DUA, credentialing, etc is satisfied.

**Comment by briangow** [comment]
This link is now only displayed if the user has access to the waveform files.
