### ISSUE TITLE
Credential Application Issues

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#180]
To fix:
- [x] Race conditions allows multiple simultaneous applications
- [x] Application form should be separated into sections
- [x] Contact reference email content should be editable textbox
- [x] Unsuccessful applications are not shown properly
- [x] Having the reference put their name for confirmation is quite useless

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/281
