### ISSUE TITLE
Project API: Provide versioning information

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1810]
In https://github.com/MIT-LCP/physionet-build/pull/1697 we added a new API endpoint that serves information about projects (1.  a list of project metadata, and 2. details about a specific project).

The endpoint for detailed project information is (e.g.): http://localhost:8000/api/v1/published/demowave/1.0.0. Right now we don't provide a mechanism for finding this path, because versioning information is not available through the API.

We should (1) add versions to the project list at http://localhost:8000/api/v1/published (2) Consider serving core project information at http://localhost:8000/api/v1/published/demowave/

**Comment by tompollard** [comment]
We should probably also provide the publication date for each version.

**Comment by Rutvikrj26** [comment]
- [x] Versioning Information already added in Issue #1842 

Provide more information on "consider serving core project information at http://localhost:8000/api/v1/published/demowave/"

what is covered in the "core project information"

**Comment by tompollard** [comment]
Versioning details are now available at (e.g.): https://physionet.org/api/v1/project/published/wfdb/. Thanks @Rutvikrj26, I'm going to close this issue as addressed.

> Provide more information on "consider serving core project information

I think we can ignore this for now, but I may open a new issue in future. One example of core project information is the "core DOI". All projects have a version-specific DOI, plus an additional core-project DOI referring to the project as a whole (which points to the latest version of the project).
