### ISSUE TITLE
Send a reminder before auto rejecting credentialing applications.

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1843]
Related to https://github.com/MIT-LCP/physionet-build/issues/1833

on [1833](https://github.com/MIT-LCP/physionet-build/issues/1833) , we are introducing change that will automatically delete credentialing application with `Awaiting Reference Response` pending.

So shouldn't we add something that sends a reminder or somekind of notification to the references or the user(although we could also expect the users to followup with their reference as i assume credentialing is important part of getting access to data)

on the other hand, it might be bunch of extra work for little gain

**Comment by tompollard** [comment]
@amitupreti I had exactly the same thought yesterday evening. I agree, I think this would be a good idea. e.g.


> Dear X,
> 
> We contacted your reference on X, but have not received a response. If we do not receive a response by X, your application will be closed.

**Comment by superryeti** [comment]
This would also be similar implementation like the 1833, right? as it sounds like something we would do in batch. 
i will add a PR for this after [1833](https://github.com/MIT-LCP/physionet-build/issues/1833).

**Comment by tompollard** [comment]
@amitupreti Yeah, dealing with these as a batch makes sense to me.
