### ISSUE TITLE
Tests failing on new Docker image due to git's safe dir feature.

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1844]
Tests are now failing with the following error (blocking all new PRs):

```
Run ./test-upgrade.sh -v origin/production
fatal: detected dubious ownership in repository at '/__w/physionet-build/physionet-build'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/physionet-build/physionet-build
Error: Process completed with exit code 12[8](https://github.com/MIT-LCP/physionet-build/actions/runs/4045502781/jobs/6957097553#step:8:9).
```

As noted by @kshalot in https://github.com/MIT-LCP/physionet-build/issues/1832#issuecomment-1408917087:

> My guess would be that the new Docker image has a newer version of Git that now includes the safe dir feature.

**Comment by bemoody** [comment]
That bug happened ages ago, weird that it's just being pushed to bullseye-security *now* (looks like it was build last week and presumably just uploaded today, there's still no Debian security advisory yet.)

Presumably we should do what it says. :)

**Comment by bemoody** [comment]
(I don't follow the details entirely, but looks like actions/checkout has its own workaround that involves creating a temporary home directory.)

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/1845
