### ISSUE TITLE
Remove Host's name from the "Event Registration" page

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1858]
When someone is invited to an event, they see the following information:

![Screenshot 2023-02-07 at 1 41 01 PM](https://user-images.githubusercontent.com/822601/217336502-e77e0ef3-8c79-4fcc-bbe2-4f7aaa0e420d.png)

We should reconsider what we display on this page. e.g.: we probably want to remove the Host's name from the page. In general, I think the title is sufficient.

**Comment by tompollard** [comment]
We might also want to add a short sentence that explains the registration process (e.g. "After clicking confirm, you will be added to a waiting list for the event. You will receive a notification to let you know when you have been successfully registered.").

**Comment by tompollard** [comment]
- Should the description be displayed on this page too?
- Also, is "You have been invited" the right language to use? Is it true that the person has been invited?

**Comment by superryeti** [comment]
Noted. I also remember we had a discussion about the registration page being separate from the event detail page(public view)

1. Invitation/event registration page  - the page where users and request to join the waiting list for event or join the event directly in case of public event
2. Event detail page - a page that displays details of events for participants, organizers, host etc. If i remember correctly, this page should show details depending on the access(like if the participant is on waitlist, they can see only minimal information, and once approved they can see the details of the event, like maybe host name, dua, etc

@tompollard  Do you think it makes sense to have
1. For the registration page, something like /events/slug/invitation
2. For the event detail page to have /events/slug
3. 
or maybe we use the current url and once someone joins the waiting list, they can see the event detail page. (this sound unnecessarily complicated as then we will have to think about what do we do if someone had already applied and got rejected, do we show them the registration page or the detail page

**Comment by superryeti** [comment]
> * Should the description be displayed on this page too?
> * Also, is "You have been invited" the right language to use? Is it true that the person has been invited?

I had the same questions,

Regarding the first one,  if we plan to have a separate event detail page, maybe we could say something like. You can find the event detail here.(and also add a button in the event detail page, so that people can request access to the event)

Or if we plan to just have the description here, I think its a good idea to show the information in table like format, like the console event detail page(In this case i think we show the start, end date , description, maybe something like x days  before the registration closes)

**Comment by superryeti** [comment]
> * Also, is "You have been invited" the right language to use? Is it true that the person has been invited?

Thats a good question. My understanding was that the event host/or organizers will share the event  url to the students(hence the language), But i remember we had discussed that in future, there will be public events, so users should be able see the event listed on event page and request for registration. So changing the language here makes sense to me

Do. you think maybe we could just have `Event Registration` as title, and event details like event title, dates, description and a sentence saying `click confirm if you want to join the waiting list`

**Comment by superryeti** [comment]
@alistairewj  tagging you for feedback

**Comment by alistairewj** [comment]
My thoughts are a page structure similar to the below:

```html
    <h2 class="form-signin-heading">Event Registration</h2>
    <p>Event name: {{ event.title }}</p>
    <p>Event type: {{ event.category }}</p>
    <p>Description: {{ event.description }}</p>
    <p>Start date: {{ event.start_date }}</p>
    <p>End date: {{ event.end_date }}</p>
    <p>Hosted by: {{ event.host.get_full_name }}</p>
    <br>
    <p>You may request to join this event below.</p>
    <form  method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-primary" name="confirm_event" value="confirm" role="button">Request Participation</button>
    </form>
    <p>Requesting participation adds your details to a waiting list. You will receive a notification when your request has been processed."
```

(N.B. Not sure if the attribute is actually `event.description`.)

This page:

* [x] Informs them of the process of requesting participation
* [x] Is agnostic to being invited / joining a public event
* [x] Can be used both before and after someone has joined an event by modifying the template to not show the request participation button
    * We decided one public event page would be best, if we can manage it, so let's try to implement that. 

Feel free to play with the formatting depending on how it looks, this is just a suggestion. Probably the button name should be changed from confirm to request as well.

**Comment by alistairewj** [comment]
I actually think keeping the host name there is useful as students may use it to confirm they have the right course.

**Comment by tompollard** [comment]
I think your suggested page structure is an improvement on what we have now, so that's good with me (other than the point below). 

> I actually think keeping the host name there is useful as students may use it to confirm they have the right course.

I agree it may sometimes be useful, but other times it may cause problems. e.g. a student has been tasked with managing the event for the instructor, now the student's name is listed instead of the instructor. For this reason, I think it is best to omit and then come up with a better approach later. It needs to be either (1) optional or (2) customisable. If someone wants to display the instructor's name, they can put it in the description for now.

**Comment by alistairewj** [comment]
Yeah that's fair.

**Comment by superryeti** [comment]
> I agree it may sometimes be useful, but other times it may cause problems. e.g. a student has been tasked with managing the event for the instructor, now the student's name is listed instead of the instructor. For this reason, I think it is best to omit and then come up with a better approach later. It needs to be either (1) optional or (2) customisable. If someone wants to display the instructor's name, they can put it in the description for now.

@tompollard @alistairewj For this, do you think we could do the following 

1 . Have another model called EventManager 
2. The host can add/edit/remove  event manager(s) after creating an event. 
3. Event manager can be anyone who is either a participant or host themselves
4. if there is(are) event manager, the Event detail page will show their name and email

**Comment by superryeti** [comment]
If we do the above, we wont need to add the checkbox on the participation list

![image](https://user-images.githubusercontent.com/24412619/217692162-9fc556dd-241b-44c1-bc49-9987fb827dec.png)

**Comment by alistairewj** [comment]
I think we will need a model like `EventManager` eventually, so I'm happy for it, except:

> 4. if there is(are) event manager, the Event detail page will show their name and email

Probably this should be a configuration option on the event detail page, to show a subset of event managers.

**Comment by superryeti** [comment]
> Probably this should be a configuration option on the event detail page, to show a subset of event managers.

For the immediate changes(before the Datathon), We might get away by putting the contact information on the description.

**Comment by alistairewj** [comment]
Yes, I think so!

**Comment by superryeti** [comment]
Closing this, as we have moved the Events discussion to shortcut. 
And the issue mentioned here was fixed and merged.
