### ISSUE TITLE
odd events bug: superuser can't see the event that they  are registered to/or on waiting list

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1878]
On Events app, i noticed a weird bug(probably not important as i doubt that this workflow will happen in real)

Bug:
Suppose  we have an event created by user x. 
And now suppose the superuser joins the event and is added to waitlist. if the super user visits the events page, they wont see the event listed on their dashboard(For other users, they will see the event that they registered for)

The reason this happens is because on events views.py the logic to display the list of events to any user is
1. if the current user is instructor(has permission to create an event), then show the events that this user created
2. else show the events the current user is registered to or is waiting for a decision

Since the super user is omnipotent and has all the permissions in the system, events app will regard the super user as instructor, and only show the events that was created by super user(Hence super user cant see the event that they registered to)

**Comment by bemoody** [comment]
Sounds like a general problem - instructors ought to be able to join
other people's events!

**Comment by superryeti** [comment]
oh yes. Thats right @bemoody . Good catch. I didn't think about that(Good thing  i opened the issue)

I will open a PR for this.

Thanks

**Comment by superryeti** [comment]
fixed by https://github.com/MIT-LCP/physionet-build/pull/1865/commits/b2707369cb5a8a9431d01410d4bab29eca23777a
