### ISSUE TITLE
Increase maximum length of event titles (currently 64 characters)

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1910]
Currently the maximum length of the title for an event is 64 characters.

https://github.com/MIT-LCP/physionet-build/blob/2a8634f0cb778753d6dd939a3203a9fe02887b70/physionet-django/events/models.py#L12-L21

This limit has caused issues with test users (for example, @xborrat has an event whose title has been truncated to something like this: " prioritisation and organization of biomedical Information and Knowledg"

Can we increase the word limit to an arbitrarily bigger but not too big number (128 characters?).

**Comment by superryeti** [comment]
Thanks Tom, i can work on this later today.
