### ISSUE TITLE
New layout for CITI Course Instructions Page

### ISSUE THREAD

**Issue by mscanlan-git** [MIT-LCP/physionet-build#1962]
The CITI course instructions page is a bit jarring to view as a new user who isn't familiar with the platform as the layout is more complicated than it needs to be. We can simplify this layout by taking the instructions and integrating them into the screenshots so that users don't need to refer to figures every time they are trying to follow said instructions. 

This is currently what the layout looks like: 

<img width="834" alt="Screenshot 2023-03-31 at 12 08 35 PM" src="https://user-images.githubusercontent.com/67070862/229173389-cc8e9f56-7e78-46d0-ac67-63926b39e743.png">

My proposed new layout would look like this:

<img width="825" alt="Screenshot 2023-03-31 at 12 05 03 PM" src="https://user-images.githubusercontent.com/67070862/229173552-0e9023b1-d668-4605-82af-01ad05f92432.png">

The actual content (images and text) will be updated to better reflect what the new CITI course website layout looks like, plus, simplifying the language and instructions by making the navigation easier for new users. The images and text will be updated in a future issue/pull request, but for now, I wanted to demonstrate what the new layout would like with the text paired with the images that are associated with it.

I am looking for feedback on this new layout and would like any criticism that could better improve it. Thanks.

_Again, please ignore the actual images and text, this will be updated._

**Comment by tompollard** [comment]
@mscanlan-git I agree that the [current layout](https://physionet.org/about/citi-course/) could be improved. In your proposed layout, I think the sequence of steps gets a little lost.  Instead, could we display the text prompts and screenshots in order, similar to the example below?: 

> 1. If your institution is affiliated with the CITI program, please log in to the CITI site using your institutional portal. Otherwise, visit the CITI program site: https://www.citiprogram.org/, create an account if you don’t already have one, and log in.

> IMAGE 1

> 2. Once you are logged in to the CITI site, open the tab “Click here to affiliate with another institution” and click on the link (fig 1)). Select your organizational affiliation as “Massachusetts Institute of Technology Affiliates”.

> IMAGE 2

> 3. After affiliating with MIT, follow the links to add a Massachusetts Institute of Technology Affiliates course (fig 2). In the Human Subjects training category, select the “Data or Specimens Only Research” course (fig 3). Answer the other questions as appropriate and submit the form.

> IMAGE 3

> etc...

**Comment by mscanlan-git** [comment]
> @mscanlan-git I agree that the [current layout](https://physionet.org/about/citi-course/) could be improved. In your proposed layout, I think the sequence of steps gets a little lost. Instead, could we display the text prompts and screenshots in order, similar to the example below?:

Yes, I agree. I think setting the page up to be vertical instead of the block formation it's in now would be better (my new instructions layout is roughly 4-5 steps, shouldn't be too lengthy).

**Comment by mscanlan-git** [comment]
@tompollard Were you thinking something like this?

<img width="699" alt="Screenshot 2023-03-31 at 2 42 10 PM" src="https://user-images.githubusercontent.com/67070862/229203845-d93e0fbb-7f3a-4ebc-a99a-548a3b16139f.png">

**Comment by tompollard** [comment]
Yep, something more like this! Some random thoughts:

1. I think including the list items (1,2,3) helps with navigation
2. I'd drop the horizontal rule below the "In order to become..." paragraph
3. Try to match the width of the images
4. Left align everything. It will look tidier. We can play around with repositioning images later.

e.g. something like this (but without repeating the same image each time!):

```
{% extends "base.html" %}

{% load static %}

{% block title %}CITI Course Instructions{% endblock %}

{% block content %}
<div class="container">
  <h1>CITI Course Instructions</h1>
  <hr>
  <p>In order to become a <a href="{% url 'edit_credentialing' %}">credentialed</a> {{ SITE_NAME }} user and access the restricted-access clinical databases, 
     you must complete a suitable training program in human research subject protections and HIPAA regulations. We recommend the Collaborative Institutional 
     Training Initiative (CITI) Program's “Data or Specimens Only Research” course. Follow the instructions below to access and complete the training course:</p>
  <ol>
    <li>If your institution is affiliated with the CITI program, please log in to the CITI site using your institutional portal. Otherwise, visit the CITI program site: <a href="https://www.citiprogram.org/">https://www.citiprogram.org/</a>, create an account if you don’t already have one, and log in.</li>
    <img src="{% static 'images/about/citi-instructions-1.png' %}" alt="Citi course instructions 1" style="width:600px">
    <li>Once you are logged in to the CITI site, open the tab “Click here to affiliate with another institution” and click on the link <em>(fig 1)</em>). Select your organizational affiliation as “Massachusetts Institute of Technology Affiliates”.</li>
    <img src="{% static 'images/about/citi-instructions-1.png' %}" alt="Citi course instructions 1" style="width:600px">
    <li>After affiliating with MIT, follow the links to add a Massachusetts Institute of Technology Affiliates course <em>(fig 2)</em>. In the Human Subjects training category, select the “Data or Specimens Only Research” course <em>(fig 3)</em>. Answer the other questions as appropriate and submit the form.</li>
    <img src="{% static 'images/about/citi-instructions-1.png' %}" alt="Citi course instructions 1" style="width:600px">
    <li>Complete the course. This may take a few hours.</li>
    <img src="{% static 'images/about/citi-instructions-1.png' %}" alt="Citi course instructions 1" style="width:600px">
    <li>When you have completed the course, generate a pdf of the completion report <em>(fig 4)</em> which you will need to <a href="{% url 'credential_application' %}">apply</a> for {{ SITE_NAME }} credentialing. The CITI completion report lists all modules completed, with dates and scores. Do NOT upload the completion certificate.</li>
    <img src="{% static 'images/about/citi-instructions-1.png' %}" alt="Citi course instructions 1" style="width:600px">
  </ol>

  <hr>
</div>
{% endblock %}

{% block local_js_bottom %}
<script src="{% static 'custom/js/enable-popover.js' %}"></script>
{% endblock %}
```

...which looks like:

![Screenshot 2023-03-31 at 3 12 24 PM](https://user-images.githubusercontent.com/822601/229209028-f8fda620-f82d-442a-b605-042818023403.png)

Not especially pretty, but easy to follow!

**Comment by tompollard** [comment]
(BTW, I think with the layout suggested above we could drop the figure legends and "Fig X" references).

**Comment by mscanlan-git** [comment]
@tompollard Thanks for the feedback, I implemented your changes on my branch. I have the screenshots that I would like to use instead of the ones we currently have (as well as the steps/directions on how to navigate based on those screenshots) I can save this for a future issue/pull request once we're happy with the page layout. 

If there's nothing else that we would like to add right now, I will open a pull request with these changes.

**Comment by tompollard** [comment]
> If there's nothing else that we would like to add right now, I will open a pull request with these changes.

Great, thanks Michael. Please go ahead with the pull request!
