### ISSUE TITLE
Should we allow curly apostrophe “” on Credentialing form-> Research Summary?

### ISSUE THREAD

**Issue by superryeti** [MIT-LCP/physionet-build#1972]
**Context:** 
We were just having someone test the https://healthdatanexus.ai/ platform, and they were going though the process of applying for Credentialing. They were unable to submit the form because the keyboard somehow added a curly apostrophe instead of straight apostrophe.

Something like this will not go through

> this is a test “lorem ipsum” This is a test description lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem 

@january-adams also found that this will happen if a user write the description in google doc or microsoft docs, and try to copy and paste it to the form

Maybe instead of adding new allowed special characters, we could add some kind of processor to clean and convert the special characters to normal ones(like from curly to straight apostrophe)

**Comment by tompollard** [comment]
I think the text validators that we use are too strict, so wouldn't be against making them more permissive.

> Maybe instead of adding new allowed special characters, we could add some kind of processor to clean and convert the special characters to normal ones(like from curly to straight apostrophe)

Also fine with me! @bemoody do you have a preference?

**Comment by alistairewj** [comment]
After an intense discussion, we decided to just allow curly apostrophes. 😠
