### ISSUE TITLE
Tracked file is being edited by compilestatic

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1989]
I should have been more careful before merging https://github.com/MIT-LCP/physionet-build/pull/1986. I now see that one of the tracked files is being edited:

After running `python manage.py compilestatic`, git diff shows:

```
	modified:   static/custom/css/home.css
```

Will wait until Monday to work out how to address this...

**Comment by superryeti** [comment]
solved by https://github.com/MIT-LCP/physionet-build/pull/1991
