### ISSUE TITLE
User search should include last name

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1990]
The search tool at http://localhost:8000/console/users/active/ searches based on the person's first name(s), username, and primary email address, but not their *last name*.

(This may have gone unnoticed because so often people have their last name as part of their email address.)

**Comment by tompollard** [comment]
@mscanlan-git if you have time, do you want to give this a go? I can help out. It is a similar change to the one at: https://github.com/MIT-LCP/physionet-build/pull/1984/files (i.e. you are editing the same search query, but this time to search the lastname).

**Comment by mscanlan-git** [comment]
@tompollard Sure, can we talk a bit about this on Tuesday? Have some questions about testing and making sure I'm using a proper approach.

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/1999
