### ISSUE TITLE
Adding link to CITI course website on Instructions page

### ISSUE THREAD

**Issue by mscanlan-git** [MIT-LCP/physionet-build#1993]
The new CITI course instructions page is live and provides a more detailed description of how to register and complete the CITI training requirements we ask of credentialed users. One issue with this page is we don't specify how to access CITI course. The best way to solve this is by simply providing a link in the opening of the instructions page so people can navigate to the website to get started.

Here is the proposed layout: 

<img width="1171" alt="Screenshot 2023-05-04 at 10 42 38 AM" src="https://user-images.githubusercontent.com/67070862/236244133-c36c48fe-b164-4568-97c9-89496b7a4e86.png">

I also adjusted the first step to tell users how to navigate to the affiliation page to get started. I want to get some feedback on whether or not it would be better to include a new step prior to the first one with a screenshot showing how to navigate to the course selection, or if it's straightforward enough that we don't need to provide directions for this step.

**Comment by tompollard** [comment]
@mscanlan-git looks good to me. Please open a pull request with your proposed changes. One minor thing...there should be a space after `CITI Program.` (before `You...`).

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/1994
