### ISSUE TITLE
Reduce word count for research summary

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#2000]
In #1824 we added a minimum word count of 20 words for the research summary description during credentialing. One of our team members has onboarded ~10-20 people now, walking them through the credentialing process, and not a single one wrote a research summary that was at least 20 words. We think the requirement is too high.

Thoughts about reducing it to 10 words, and/or adding an env var to control it? An env var seems overkill, but maybe we do want it to be configurable for deployments.

**Comment by alistairewj** [comment]
P.S. Happy 2000th issue physionet-build! Feels a bit anti-climactic to be talking about word counts 😂

**Comment by superryeti** [comment]
> In #1824 we added a minimum word count of 20 words for the research summary description during credentialing. One of our team members has onboarded ~10-20 people now, walking them through the credentialing process, and not a single one wrote a research summary that was at least 20 words. We think the requirement is too high.
> 
> Thoughts about reducing it to 10 words, and/or adding an env var to control it? An env var seems overkill, but maybe we do want it to be configurable for deployments.

Quick note, we already have the env variable to control wordcount.

https://github.com/MIT-LCP/physionet-build/blob/28a8d047da4e28a30cd9936160e159cad8d130b6/.env.example#L184-L185

**Comment by tompollard** [comment]
>  One of our team members has onboarded ~10-20 people now, walking them through the credentialing process, and not a single one wrote a research summary that was at least 20 words

Thanks for raising this. We should think about reducing the number of words in our `.env` file too then (we could drop the number in the `.env.example` if you think this is a good idea).

**Comment by alistairewj** [comment]
> > In #1824 we added a minimum word count of 20 words for the research summary description during credentialing. One of our team members has onboarded ~10-20 people now, walking them through the credentialing process, and not a single one wrote a research summary that was at least 20 words. We think the requirement is too high.
> > 
> > Thoughts about reducing it to 10 words, and/or adding an env var to control it? An env var seems overkill, but maybe we do want it to be configurable for deployments.
> 
> Quick note, we already have the env variable to control wordcount.
> 
> https://github.com/MIT-LCP/physionet-build/blob/28a8d047da4e28a30cd9936160e159cad8d130b6/.env.example#L184-L185

Oh I missed us adding this as an env var! All's well then.
