### ISSUE TITLE
Process for pinning physionet-data project on BigQuery has changed

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2009]
I'm not sure exactly when this happened, but BigQuery updated the project search tool so that `physionet-data` is no longer findable using our existing instructions. The new process for pinning `physionet-data` is as follows (thanks @xborrat for helping to work this out!):

1. Add email address for Google Cloud account at: https://physionet.org/settings/cloud/
2. Request access on Google BigQuery via the relevant project on PhysioNet (e.g. https://physionet.org/content/mimiciv/)

> . 
> .   
> ![Screenshot 2023-05-22 at 11 17 57 AM](https://github.com/MIT-LCP/physionet-build/assets/822601/2641d52c-1399-4b34-9f9b-fb9e535faf4c)
>. 
>. 

3. Login to the [BigQuery console](https://console.cloud.google.com/bigquery) and click the "Add data" button

>. 
>. 
> ![Screenshot 2023-05-22 at 11 21 26 AM](https://github.com/MIT-LCP/physionet-build/assets/822601/9829789e-19d5-46c4-970c-45998c41085c)
>. 
>. 

4. Select "Star a project by name"

>. 
>. 
>  ![Screenshot 2023-05-22 at 11 09 22 AM](https://github.com/MIT-LCP/physionet-build/assets/822601/b1211454-af39-4086-babb-f87b54f05b1f)
>. 
>. 

5. Type "`physionet-data`" into the "Star a project" form.

>. 
>. 
>  ![Screenshot 2023-05-22 at 11 09 31 AM](https://github.com/MIT-LCP/physionet-build/assets/822601/af78b4af-f849-4d26-8263-5e1c15162e16)
>. 
>. 

6. That's it! `physionet-data` should now appear in your list of resources.

>. 
>. 
> <img width="701" alt="Screenshot 2023-05-22 at 11 29 34 AM" src="https://github.com/MIT-LCP/physionet-build/assets/822601/f4941ed2-3189-44ef-854c-13bcebef1bf6">
>. 
>.

**Comment by alistairewj** [comment]
Merged some improvements in #2014
