### ISSUE TITLE
TypeError (argument of type 'NoneType' is not iterable): if '@' in username

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2034]
We are seeing multiple versions of the following error, across multiple projects. The error seems related to the recent update in https://github.com/MIT-LCP/physionet-build/pull/2003 to introduce OAuth support.

The `HTTP_USER_AGENT` looks suspicious! In all errors the agent is either `Microsoft Office Excel 2014`,`Microsoft Office PowerPoint 2014`; or `Microsoft Office Word 2014`.

```
Internal Server Error: /files/SLUG/1.0/FOLDER/


TypeError at /files/SLUG/1.0/FOLDER/
argument of type 'NoneType' is not iterable

Request Method: HEAD
Request URL: 
Django Version: 4.1.9
Python Executable: /home/physionet/python-env/physionet/bin/uwsgi
Python Version: 3.9.2
Python Path: ['.', '', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/physionet/python-env/physionet/lib/python3.9/site-packages']

Traceback:

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/exception.py" in inner
 56.                 response = get_response(request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/oauth2_provider/middleware.py" in __call__
 32.                 user = authenticate(request=request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/views/decorators/debug.py" in sensitive_variables_wrapper
 42.             return func(*func_args, **func_kwargs)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/contrib/auth/__init__.py" in authenticate
 77.             user = backend.authenticate(request, **credentials)

File "./user/backends.py" in authenticate
 15.         if '@' in username:

Exception Type: TypeError at /files/SLUG/1.0/FOLDER/
Exception Value: argument of type 'NoneType' is not iterable
Request information:
USER: [unable to retrieve the current user]

GET: No GET data
POST: No POST data
FILES: No FILES data
COOKIES: No cookie data

META:
HTTP_USER_AGENT = 'Microsoft Office Excel 2014'
REMOTE_ADDR = 'XXXXXX'
```

**Comment by Rutvikrj26** [comment]
I tried recreating the issue using the Demo version but was unsuccessful. 
While checking the Oauth - one of the things that might help is changing the order of the middleware and keeping the default authentication `django.contrib.auth.middleware.AuthenticationMiddleware` on top of Oauth Middleware `oauth2_provider.middleware.OAuth2TokenMiddleware`(which should have been done by me earlier). In the current order, the Authentication works fine on browser-based access, but there might be some corner cases where it might fail, as in this case, when people might be accessing the platform from clients other than browsers(as in this case using a powerquery probably).

>If you put the OAuth2 backend after the AuthenticationMiddleware and request.user is valid, the backend will do nothing; if request.user is the Anonymous user it will try to authenticate the user using the OAuth2 access token.

>If you put the OAuth2 backend before AuthenticationMiddleware, or AuthenticationMiddleware is not used at all, it will try to authenticate user with the OAuth2 access token and set request.user and request._cached_user fields so that AuthenticationMiddleware (when active) will not try to get user from the session.

The default Authentication middleware should ideally be on the top(in general as well). I'm opening a branch to make this change.
