### ISSUE TITLE
Authorization: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2040]
Since the addition of https://github.com/MIT-LCP/physionet-build/pull/2003, we have been regularly seeing an `argument of type 'NoneType' is not iterable` error:

```
Internal Server Error: /content/autonomic-aging-cardiovascular/

TypeError at /content/autonomic-aging-cardiovascular/
argument of type 'NoneType' is not iterable

Traceback:

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/exception.py" in inner
 56.                 response = get_response(request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/oauth2_provider/middleware.py" in __call__
 32.                 user = authenticate(request=request)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/views/decorators/debug.py" in sensitive_variables_wrapper
 42.             return func(*func_args, **func_kwargs)

File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/contrib/auth/__init__.py" in authenticate
 77.             user = backend.authenticate(request, **credentials)

File "./user/backends.py" in authenticate
 15.         if '@' in username:

Exception Type: TypeError at /content/autonomic-aging-cardiovascular/
Exception Value: argument of type 'NoneType' is not iterable
Request information:
USER: AnonymousUser

GET: No GET data
POST: No POST data
FILES: No FILES data
COOKIES: No cookie data
```

The error can be reproduced with:

```
curl -H user-agent:'Microsoft Office Word 2014' -H accept-auth:'badger,Wlid1.1,Bearer,Basic,NTLM,Digest,Kerberos,Negotiate,Nego2' -H authorization:'Bearer' localhost:8000
```

See also: https://github.com/MIT-LCP/physionet-build/pull/2037.  For now a temporary fix is: https://github.com/MIT-LCP/physionet-build/pull/2039

@bemoody's suggestions/notes on this issue:

1. Our custom authorization (`DualAuthModelBackend`) does not seem to be behaving in the way that Django expects it to behave. We should look at the current authorization module and compare to our implementation.
2. It is possible that the fix in https://github.com/MIT-LCP/physionet-build/pull/2039 will break OAuth.
3. We need to better understand the OAuth module and work out what it is doing. We could consider temporarily removing the OAuth middleware in the meantime.

**Comment by Rutvikrj26** [comment]
#2039 does not break OAuth. Tested the functionality - works as intended.

**Comment by bemoody** [comment]
Regarding point 1, here is the standard `authenticate` function as defined by Django 4.1.10 (django/contrib/auth/backends.py):
```
    def authenticate(self, request, username=None, password=None, **kwargs):
        if username is None:
            username = kwargs.get(UserModel.USERNAME_FIELD)
        if username is None or password is None:
            return
        try:
            user = UserModel._default_manager.get_by_natural_key(username)
        except UserModel.DoesNotExist:
            # Run the default password hasher once to reduce the timing
            # difference between an existing and a nonexistent user (#20760).
            UserModel().set_password(password)
        else:
            if user.check_password(password) and self.user_can_authenticate(user
):
                return user
```
So it would probably be best for our `authenticate` function to work the same way (it should ignore unknown keyword arguments, and should return None if either username or password is None.)

(The way Django actually *invokes* the backend authenticate functions is positively wacky.)

Anyway, I still don't understand how OAuth fits into this exactly.

**Comment by bemoody** [comment]
Regarding points 2 and 3, I think @Rutvikrj26 said that OAuth appears to be working now?  However, we should add one or more test cases for the OAuth client workflow (check that a demo user can obtain an OAuth token, and then use that token to access a protected resource.)
