### ISSUE TITLE
Projects with no authors

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2048]
Following active projects have *no authors*:
```
'g2c7vWhNrlHgpnZDnzWd',
'2h0NLYGG2cwiKwiSeQxN',
'D2KkjITMQlDs1c17gAOu',
'pe3WGD2P3HxzxPLfuFH9',
'oBInBp72u8fkzT5xqlVr',
'iwHaFSsdG5ps4qg3RjL7',
'7pXKAImYKGUpkswpqBLa'
```
This shouldn't happen... any idea why?  All of these projects appear to be spam (they also have no files.)  The projects were apparently created at different times between last December and June.

**Comment by tompollard** [comment]
@bemoody possibly my bad and we should chat. I recently deleted a bunch of spam users, which could explain this. I was trying to be careful not to delete users associated with projects, but possibly I wasn't being as careful as I thought.

**Comment by bemoody** [comment]
In that case probably nothing to worry about and we can just delete these projects.  It would be worrying if there was some corner case that caused authors to be detached from their projects.

As a general matter, though, we are using `on_delete=models.CASCADE` in a lot of places that seem risky (`BaseAuthor` is just one of many), and it would be wiser in my view to use `models.PROTECT` to ensure that programmers and administrators make their intentions clear.

**Comment by bemoody** [comment]
Deleted these ActiveProjects.

**Comment by tompollard** [comment]
Thanks!
