### ISSUE TITLE
When changing a project's access policy to open, a file embargo can be applied without indication

### ISSUE THREAD

**Issue by briangow** [MIT-LCP/physionet-build#2076]
The file embargo option is not supposed to be applied to open access projects. There is code in place which prevents setting an embargo on an open access project. However, if a project was previously set with an access policy other than open and a new version of the project is created, the embargo is carried forward. This is the case even if the project is changed to open in a new version. In this case, the editor would assume that no embargo is being applied based on the message in the console "The files for an open access project cannot be placed under embargo."

We should fix this by doing one of these two things:

1. Prevent carrying the embargo forward when creating a new project version. This would require the editor to explicitly set the embargo each time a new version of a project is published. 
2. Update the code to clear `embargo_files_days` when the access policy is set to open.

**Comment by tompollard** [comment]
> The file embargo option is not supposed to be applied to open access projects.

I might be misremembering, but I think the reason that we do not embargo open access projects is that it was more complicated to implement, because open access files live in a publicly-accessible folder? I think it is desirable to be able to embargo all projects, regardless of the license or usage terms.

**Comment by bemoody** [comment]
> I think it is desirable to be able to embargo all projects, regardless of the license or usage terms.

Agreed that is something we should support and should open a separate issue about this :)

It also may be worth implementing a short term solution to avoid accidentally setting an embargo that won't be enforced.  This is more or less the same issue as #1759.

**Comment by briangow** [comment]
Agreed, this is mostly covered in #1759 so I probably shouldn't have opened a separate issue for this. I will refer to this discussion there and close this issue.
