### ISSUE TITLE
Setting requester-pays for google cloud buckets

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2079]
When we create public Google Cloud buckets, we probably want them to be "requester-pays" unless we have a specific arrangement for somebody to cover download costs.

Is this currently being done by default (i.e. when the bucket is created through the PhysioNet admin console)?  Can we make this an explicit option in the console?

**Comment by tompollard** [comment]
> Is this currently being done by default (i.e. when the bucket is created through the PhysioNet admin console)?

No, it is not set by default as far as I am aware.
> Can we make this an explicit option in the console?

Yes, we should do this!

**Comment by bemoody** [comment]
`google.cloud.storage.Client.create_bucket` takes an argument `requester_pays`, but this is "DEPRECATED. Use Bucket().requester_pays instead."

Not totally clear what's going on here (what is "bucket_policy_only_enabled"?)
```
    storage_client = storage.Client()
    bucket_name, email = bucket_info(project, version)
    storage_client.create_bucket(bucket_name)
    bucket = storage_client.bucket(bucket_name)
    bucket.iam_configuration.bucket_policy_only_enabled = True
    bucket.patch()
```

but maybe it should look something like this instead?
```
    storage_client = storage.Client()
    bucket_name, email = bucket_info(project, version)
    bucket = storage_client.bucket(bucket_name)
    bucket.iam_configuration.bucket_policy_only_enabled = True
    bucket.requester_pays = True
    storage_client.create_bucket(bucket)
```

**Comment by bemoody** [comment]
> what is "bucket_policy_only_enabled"?

It's a deprecated alias for `uniform_bucket_level_access_enabled` (see google/cloud/storage/bucket.py).  physionet/gcs.py uses `uniform_bucket_level_access_enabled` instead.

What it means is that there are no per-file access permissions - only a single access policy for the entire bucket.  See https://cloud.google.com/storage/docs/uniform-bucket-level-access

**Comment by bemoody** [comment]
Welp

```
Exception Type: BadRequest at /console/published-projects/phdsm/1.1/
Exception Value: 400 GET https://storage.googleapis.com/storage/v1/b/phdsm-1.1.physionet.org/iam?prettyPrint=false: Bucket is a requester pays bucket but no user project provided.
```

So, it's not quite that easy.  I guess that you need to specify a billing project even if you are the bucket owner.

Weird, though, is that this exception was raised from
```
  File "./console/views.py", line 988, in gcp_bucket_management
    utility.create_bucket(project.slug, project.version, project.title, is_private)
  File "./console/utility.py", line 72, in create_bucket
    make_bucket_public(bucket)
  File "./console/utility.py", line 93, in make_bucket_public
    policy = bucket.get_iam_policy()
```

You need a billing account to query the policy?  okay then.

**Comment by bemoody** [comment]
Note that there is already a `"project_id"` specified in the `PhysioNet-Data-Credentials.json` file (`GOOGLE_APPLICATION_CREDENTIALS`).  Is that not being used?  Something else we need to do here?

**Comment by bemoody** [comment]
More information

```
>>> sc = google.cloud.storage.Client()

>>> sc.get_bucket(sc.bucket('i-care-2.0.physionet.org'))
<Bucket: i-care-2.0.physionet.org>

>>> sc.get_bucket(sc.bucket('phdsm-1.0.physionet.org'))
...
google.api_core.exceptions.BadRequest: 400 GET https://storage.googleapis.com/storage/v1/b/phdsm-1.0.physionet.org?projection=noAcl&prettyPrint=false: Bucket is a requester pays bucket but no user project provided.

>>> sc.get_bucket(sc.bucket('i-care-2.0.physionet.org', user_project=sc.project))
...
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/i-care-2.0.physionet.org?userProject=physionet-data&projection=noAcl&prettyPrint=false: storage-admin@physionet-data.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project. Permission 'serviceusage.services.use' denied on resource (or it may not exist).

>>> sc.get_bucket(sc.bucket('phdsm-1.0.physionet.org', user_project=sc.project))
...
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/phdsm-1.0.physionet.org?userProject=physionet-data&projection=noAcl&prettyPrint=false: storage-admin@physionet-data.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project. Permission 'serviceusage.services.use' denied on resource (or it may not exist).
```

Although we could roll back the previous change to get it temporarily working again, we really need to fix this issue - as it stands, we can't query or modify any of our existing requester-pays buckets, nor can we switch them back to non-requester-pays.

**Comment by bemoody** [comment]
It seems very silly and strange that the service account would have permission to create buckets and designate them as requester-pays, but would not have permission to access that bucket afterwards.

https://cloud.google.com/storage/docs/requester-pays#requirements

> To make a bucket Requester Pays, enable the metadata flag on the desired bucket. Once enabled, only the following users can access the bucket or its contents:
> 
> Requesters who include a billing project in their request. The project used in the request must be in good standing, and the user must have a role in the project that contains the serviceusage.services.use permission. The Service Usage Consumer role contains the required permission.
> 
> Requesters who don't include a billing project but have resourcemanager.projects.createBillingAssignment permission for the project that contains the bucket. The Billing Project Manager role contains the required permission. Access charges associated with these requests are billed to the project that contains the bucket.

Looking at the console "IAM & Admin" page (https://console.cloud.google.com/iam-admin/iam?project=physionet-data):

- I don't see myself listed so I have no idea why I'm allowed to view this page at all.

- The service account (storage-admin@physionet-data.iam.gserviceaccount.com) has the roles `Access Transparency Admin` and `Storage Admin`.

- Nobody has the role `Billing Project Manager` or `Service Usage Consumer`.

Looking at the "Roles" page (https://console.cloud.google.com/iam-admin/roles?project=physionet-data):

- There are a total of 1409 roles defined (yeesh.)

- There is no `Billing Project Manager`, only `Project Billing Manager`.

- Only the roles `Billing Account Administrator`, `Owner`, and `Project Billing Manager` have the permission `resourcemanager.projects.createBillingAssignment`.

- 51 roles have the permission `serviceusage.services.use` (`Storage Admin` is not one of them.)

- The `Project Billing Manager` role has permissions `resourcemanager.projects.createBillingAssignment` and `resourcemanager.projects.deleteBillingAssignment`.

- The `Service Usage Consumer` role has permissions `monitoring.timeSeries.list`, `serviceusage.operations.get`, `serviceusage.operations.list`, `serviceusage.quotas.get`, `serviceusage.services.get`, `serviceusage.services.list`, and `serviceusage.services.use`.

This is all very confusing.  But it sounds to me like:

1. If we were to grant the role `Service Usage Consumer`, then the service account would be able to access any requester-pays bucket (ours or other people's), with costs billed to physionet-data.  We'd also have to change all the logic to explicitly specify a `user_project`, because it doesn't look like there is any way to set a global default.

2. If we were to grant the role `Project Billing Manager`, then the service account would be able to access *our own* requester-pays buckets, and would not require any code changes.

**Comment by bemoody** [comment]
@elfeto or anybody who understands GCP, does this make sense to you?  I think what we want is to add the `Project Billing Manager` role.  I don't think I currenlty have permission to do so and don't know who does.

**Comment by bemoody** [comment]
Brian helped me set the permissions and hopefully it should be working now.

Let me know if anything else is not working here!
