### ISSUE TITLE
Connecting to PhysioNet URLs within MIT and/or CSAIL

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2082]
We have had a report from a colleague at MIT/CSAIL who is unable to connect to a PhysioNet URL (using both Firefox and Chrome). We should look into this, particularly if we would like to continue to benefit from support within MIT!

The problematic URL was a referee request form: `https://physionet.org/credential-reference/<SLUG1>/<SLUG2>/`. The link was fine for me, but I'm currently outside the MIT network.

1) Are we able to reproduce this issue ourselves, either from the IMES or CSAIL networks?
2) If so, how we can fix the problem?

**Comment by bemoody** [comment]
As far as I'm aware there are not currently any connectivity problems.

I think the problem had nothing to do with the network or the browser but rather that the URL was garbled (probably the person simply made a mistake copying and pasting, though it's conceivable it got mangled by a buggy mail client.)

**Comment by tompollard** [comment]
Thanks for looking into this @bemoody. I'm not convinced that it is a copy and paste error, because I believe they tried the link a couple of separate times. Possible it is a mail client issue of some sort. If we receive more complaints, we can reopen.
