### ISSUE TITLE
Failing to Add boto3 to the requirements.txt

### ISSUE THREAD

**Issue by Chrystinne** [MIT-LCP/physionet-build#2087]
I am encountering issues when attempting to add boto3 to the requirements.txt file. 

poetry add 'boto3==1.28.33'

The error message is as follows:

 *** error linking uWSGI ***

Note: This error originates from the build backend, and is likely not a problem with poetry but with uwsgi (2.0.22) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "uwsgi (==2.0.22)"'.

Any ideas on how to solve this, @bemoody?

**Comment by briangow** [comment]
@Chrystinne are you having trouble creating a local environment with `boto` in it on your mac? I've had problems with uWSGI installs on my Mac M1. Do you use brew? Currently this is what I need to do to get around it:

`LDFLAGS=-L/opt/homebrew/Cellar/gettext/0.21.1/lib pip install "uWSGI==2.0.21”` from https://github.com/unbit/uwsgi/issues/2361

You might also get an error with psycopg2. If so, this is what fixes it for me:

`ln -s $(brew --prefix)/lib/postgresql@14/libpq.5.14.dylib $(brew --prefix)/opt/postgresql/lib/libpq.5.dylib` from https://stackoverflow.com/questions/68894232/error-loading-psycopg2-module-library-not-loaded-libpq-5-dylib

**Comment by Chrystinne** [comment]
@briangow Thanks for your reply, Brian! I had a similar issue with uWSGI and psycopg2 in the past, but I was able to resolve it. So adding boto3 to my local environment recently wasn't a problem, and my code works properly.

However, when I created the PR, the tests failed because I hadn't added boto3 to the requirements.txt using Poetry. I'm encountering an error when attempting to do so.

**Comment by Chrystinne** [comment]
@briangow Do you believe that running these commands can resolve the issue? If not, maybe someone who isn't encountering any problems could attempt to update the requirements.txt to include 'boto3==1.28.33'?

**Comment by tompollard** [comment]
@Chrystinne Are you seeing the error on your local machine or on the github testing server?

**Comment by briangow** [comment]
> @Chrystinne Are you seeing the error on your local machine or on the github testing server?

This is also what I am trying to understand.

**Comment by Chrystinne** [comment]
@tompollard I was seeing the error only on the Github testing server

**Comment by tompollard** [comment]
Great, thanks @Chrystinne, I think this issue is resolved then. New error at https://github.com/MIT-LCP/physionet-build/pull/2086, but unrelated!

**Comment by Chrystinne** [comment]
@tompollard Exactly! The problem now is that those tests aren't able to find the AWS credentials.
