### ISSUE TITLE
S3: storage of service account credentials

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2095]
We want to provide mirrors of our published projects on Amazon S3 (similar to our existing Google Cloud mirrors) for purposes of providing faster and more convenient access.

To do this we need to store credentials (what boto3 calls `aws_access_key_id` and `aws_secret_access_key`) for our service account.

We might also end up needing to maintain multiple service accounts in parallel.

The boto3 library supports no fewer than eight different ways to specify credentials: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

> 1. Passing credentials as parameters in the boto.client() method
>
> 2. Passing credentials as parameters when creating a Session object
>
> 3. Environment variables
>
> 4. Shared credential file (~/.aws/credentials)
>
> 5. AWS config file (~/.aws/config)
>
> 6. Assume Role provider
>
> 7. Boto2 config file (/etc/boto.cfg and ~/.boto)
>
> 8. Instance metadata service on an Amazon EC2 instance that has an IAM role configured.

I have a slight preference for using a separate config file (option 4 or 5), similar to what we do for Google Cloud.  I don't know why there are two options or if one is better than the other.

Note that `www-data` doesn't have a (writable) home directory; if we do use a config file then we would need to override the default path.

**Comment by tompollard** [comment]
> I have a slight preference for using a separate config file (option 4 or 5), similar to what we do for Google Cloud. I don't know why there are two options or if one is better than the other.

Let's go with 4 or 5 as you suggest. I have no preference, and it makes sense to use the same approach as Google Cloud.

**Comment by bemoody** [comment]
Resolved in pull #2086.
