### ISSUE TITLE
List group membership for users in the admin console

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2105]
We now handle permissions through "groups". e.g. an event host is a member of the "host" group. We should display group membership on the user pages in the admin console (https://physionet.org/console/user/manage/USERNAME/).

e.g. on the user page, we could show:

### Permission groups

The user is a member of the following groups:

- Host
- Web editor
- etc.

**Comment by mscanlan-git** [comment]
I noticed in the code that we already display the user's group, however, I think putting this info in it's own subsection on the page would look better, especially if the user is apart of multiple groups:

<img width="881" alt="Screenshot 2023-10-11 at 2 42 57 PM" src="https://github.com/MIT-LCP/physionet-build/assets/67070862/1f49bd6c-3198-48cd-8f13-7390e9095dfc">

If this is what you had in mind, I can put a PR up for this.
