### ISSUE TITLE
S3: zip archives

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2122]
We have to decide whether and how we are going to upload *zip archives* to S3.

Personally I would rather fix issue #1674 first, but that may take some time and it would probably be wiser to upload the zip files in their current imperfect state.

Currently, pull #2086 would upload the archive for `mitdb/1.0.0` as `s3://XXXXXX/mitdb/mit-bih-arrhythmia-database-1.0.0.zip` and the files in that archive would be named `mit-bih-arrhythmia-database-1.0.0/100.hea` etc.

Preferably the archive would be named `s3://XXXXXX/mitdb/mitdb-1.0.0.zip` and a file inside the archive would be named `mitdb-1.0.0/100.hea`.

Should we:

- keep the file as `s3://XXXXXX/mitdb/mit-bih-arrhythmia-database-1.0.0.zip`, plan to remove and replace it with `s3://XXXXXX/mitdb/mitdb-1.0.0.zip` eventually?

- upload the existing file as `s3://XXXXXX/mitdb/mitdb-1.0.0.zip`, plan to replace it eventually with a different version at the same URL?

- not upload zip files to S3 at all until issue #1674 is resolved?

@chrystinne @tompollard

**Comment by tompollard** [comment]
> not upload zip files to S3 at all until issue https://github.com/MIT-LCP/physionet-build/issues/1674 is resolved?

This is tempting, but as I don't want to be responsible for holding @Chrystinne up, I think the best solution is:

> upload the existing file as s3://XXXXXX/mitdb/mitdb-1.0.0.zip, plan to replace it eventually with a different version at the same URL?

**Comment by bemoody** [comment]
Addressed by pull #2086.
