### ISSUE TITLE
List for selecting a parent project is not ordered well

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#2132]
When selecting a parent project for a publication, you can search by typing (which is great!), but you get all the projects in a really weird order (not so great):

<img width="921" alt="Screenshot 2023-11-16 at 6 25 49 AM" src="https://github.com/MIT-LCP/physionet-build/assets/1282676/a767a009-bc2c-4351-9882-4f9837b04442">

The things that would make this easier are (in order of preference):

1. Versions for the same project are grouped together. So it shows MIMIC-IV-ED v1.0, MIMIC-IV-ED v2.0, MIMIC-IV-ED v2.1, MIMIC-IV-ED v2.2 sequentially, one after another.
2. Projects are ordered alphabetically, so MIMIC-IV v1.0, MIMIC-IV v2.0, ..., MIMIC-IV-ED v1.0, MIMIC-IV-ED v2.0, ...

**Comment by tompollard** [comment]
Ordering of projects has bugged me for a long time, but not enough to fix it! Should be fixed in https://github.com/MIT-LCP/physionet-build/pull/2133.
