### ISSUE TITLE
Permissions on S3 log bucket

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2151]
I brought this up in the pull #2086 discussion but it got lost.

Currently the S3 bucket we're using for logging has permissions that (if I understand correctly) allow *anyone* to write log files into it (but not to read them.)

The access policy includes two statements.  The one called "S3PolicyStmt-DO-NOT-MODIFY-1697643261877" needs to be removed.

**Comment by Chrystinne** [comment]
You are right, @bemoody.  I just removed the "S3PolicyStmt-DO-NOT-MODIFY-1697643261877" statement from the bucket policy.

**Comment by Chrystinne** [comment]
@bemoody Now, only our open data account has permission to execute the 's3:PutObject' action. Please reopen this issue if there is still something else to be done.
