### ISSUE TITLE
Updating DOI changes publication year

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2160]
`console.utility.generate_doi_payload` generates the JSON metadata that is sent to the DataCite API, either to register, publish, or update a DOI.

This includes:
```
                "publicationYear": timezone.now().year,
```
which seems very wrong.

**Comment by tompollard** [comment]
Good catch!

**Comment by tompollard** [comment]
When creating the DOI for `core_project`s (which points to the latest version of the project), do you agree that we should set the `PublicationYear` to the latest version of the project?

**Comment by bemoody** [comment]
Yeah, I think the core project DOI info should match the latest version, including publication year.

I'm not sure what happens right now if you go to a "non-latest-version" management page and click "Update metadata (core)".
