### ISSUE TITLE
Credential column on event management page does not display a check mark for credentialed users

### ISSUE THREAD

**Issue by mscanlan-git** [MIT-LCP/physionet-build#2163]
The `credential` column on the event management page does not properly display whether or not a user is credentialed. After discussing with an event host, we discovered that a few of the credentialed users who were event participants did not show up as credentialed. 

Here is a screenshot of the table in question (removed names & emails):
![image](https://github.com/MIT-LCP/physionet-build/assets/67070862/73e840ac-084b-4ea4-8bac-78f07a8f4475)

**Comment by tompollard** [comment]
Something very wrong with the template here! The "Credentialed" column is displaying: 

```
<td>{{ object.comment_to_applicant }}</td>
```

https://github.com/MIT-LCP/physionet-build/blob/543e7164a0c7f5f218a060886fe7cff4545730ab/physionet-django/events/templates/events/event_applications.html#L7-L30
