### ISSUE TITLE
install-pn-test-server not installing rsyslog

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#2208]
On PhysioNet we use rsyslogd for managing (some) system logs.  I think this package used to be installed by Debian by default.  However, it seems it's not currently installed in the Debian 12 test-server configuration.

Probably this package should be added to install-pn-test-server.

**Comment by tompollard** [comment]
Like this? https://github.com/MIT-LCP/physionet-build/pull/2209
