### ISSUE TITLE
Exception Type: Exception at /lightwave/server Exception Value: no response header

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2236]
We are getting bombarded with error messages at the moment:

```
Internal Server Error: /lightwave/server

Exception at /lightwave/server
no response header

Traceback:

File "/physionet/python-env/physionet/lib/python3.11/site-packages/django/core/handlers/exception.py" in inner
 55.                 response = get_response(request)

File "/physionet/python-env/physionet/lib/python3.11/site-packages/django/core/handlers/base.py" in _get_response
 197.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/physionet/physionet-build/physionet-django/lightwave/views.py" in lightwave_server
 135.     return serve_lightwave(query_string=request.GET.urlencode(),

File "/home/physionet/physionet-build/physionet-django/lightwave/views.py" in serve_lightwave
 119.             raise Exception('no response header')

Exception Type: Exception at /lightwave/server
Exception Value: no response header
Request information:
USER: AnonymousUser

GET:
action = 'fetch'
db = 'mitdb/1.0.0'
record = '100'
annotator = 'atr'
dt = '0'
```

I don't want to hide legitimate errors, but we need to do something about this. The error is raised here:

https://github.com/MIT-LCP/physionet-build/blob/6f6406d3abe9e826d2a520efc7ac0cb7535ddd47/physionet-django/lightwave/views.py#L124-L139

@bemoody can we do a try/except on `return serve_lightwave(...` or do you have a better suggestion?

**Comment by bemoody** [comment]
You may notice that I've just switched PhysioNet over to the (newly upgraded) server.  The old copy of lightwave was broken by glibc and libFLAC upgrades.  Sorry I didn't think to check this in advance, and sorry that I didn't notice this immediately.

> I don't want to hide legitimate errors

Well, they don't get much more legitimate than that.  I agree that "send an email every time a request fails" is problematic, and I'd love to hear better ideas.

**Comment by bemoody** [comment]
One thought that occurs to me is "run the physionet-build test suite as part of the migration checklist".

Another thought is, could we have something like physionet.test_urls to run against the live server?

**Comment by tompollard** [comment]
> One thought that occurs to me is "run the physionet-build test suite as part of the migration checklist".
> Another thought is, could we have something like physionet.test_urls to run against the live server?

I like both of these suggestions. 

I know that you aren't sold on this, but I think moving to a containerized (Docker) approach is also worth considering. It's pretty powerful to be able to throw a container onto a server and have it running with a few simple commands. I think the issue is how this would work with the large amount of storage that we need.

(Edit: Not that this solves the issue of getting hammered by error messages when something goes wrong!)
