### ISSUE TITLE
List of training applications in admin console not in chronological order

### ISSUE THREAD

**Issue by cpitsch** [MIT-LCP/physionet-build#2263]
The training applications at https://physionet.org/console/training/review/ seem to be ordered by "Identity Verified" before the submission date. This makes it tedious to handle the applications by submission date.

For me, it seems more intuitive to first order by submission date and then by their verification status.

**Comment by tompollard** [comment]
@cpitsch let me know when you have spare 15 min and we can walk through the fix together.
