### ISSUE TITLE
NavMenus and NavLinks on admin console are not customizable

### ISSUE THREAD

**Issue by matkaczmarek** [MIT-LCP/physionet-build#2294]
When working on HDN we discovered a need for custom admin panel tabs displaying HDN specific content. For example, recently, we introduced two new admin console tabs, including Google Cloud Platform group management or custom dataset monitoring.
<img width="221" alt="image" src="https://github.com/user-attachments/assets/c6d810f3-4ef9-410a-a4bc-cded369b11e2">

To do that, currently, we need to introduce this change into the `console/navbar.py` file:
```
    NavSubmenu(_('Power Users'), 'cloud_groups', 'book', [
        NavLink(_('User Panel'), 'cloud_groups'),
        NavLink(_('Group Management'), 'cloud_groups_management'),
        NavLink(_('Group Creation'), 'create_cloud_group'),
    ]),
    NavSubmenu(_('Monitoring'), 'datasets_monitoring', 'chart-line', [
        NavLink(_('Dataset Total Usage Time'), 'get_datasets_monitoring_data'),
    ]),
```
Those tabs, from the Physionet point of view, are useless and shouldn't be visible therefore, we decided not to put them in the codebase.
From the HDN point of view, with every update to the Physionet codebase, we need to remember to apply those changes one more and potentially resolve conflicts in code leading to two major issues:
- it is easy to forget after the Physionet update that those custom changes need to be applied
- with more and more custom tabs there are more and more potential conflicts to resolve

Potential solution:

Introduce `NavSubmenu` and `NavLink` database models storing information about `title`, `icon`, `view_name` etc like:

```
class NavLink(models.Model):
    title = models.CharField(max_length=255)
    view_name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)
    enabled = models.BooleanField(default=True)
    view_args = models.JSONField(blank=True, null=True)
    order = models.IntegerField(default=0)
    is_sublink = models.BooleanField(default=True)
    
class NavSubmenu(models.Model):
    title = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)
    links = models.ManyToManyField(NavLink, related_name="submenus", blank=True)
    order = models.IntegerField(default=0) 
 ```
 and construct an admin console view based on entries stored in the database. Views and paths necessary for specific admin panel tabs could be loaded from python packages like `hdn-research-environment ` which would resolve the above issues and open the door for further customizations.

**Comment by matkaczmarek** [comment]
@tompollard @bemoody please take a look and let me know what you think about making the admin console more customizable.

**Comment by tompollard** [comment]
Without thinking through the details, at a high-level this seems reasonable to me. A couple of quick questions:

- How are permissions handled with this approach? i.e. how do I determine who can view an item in the menu?
- What is contained in `view_args`?

**Comment by bemoody** [comment]
> Those tabs, from the Physionet point of view, are useless and shouldn't be visible therefore, we decided not to put them in the codebase.

This is where I disagree.  I'd say just put them in!  Add them to the nav menu in a place that makes sense.

If the views require *special user permissions*, then use the console_permission_required decorator.

If the views require *special site configuration*, then we can use the `enabled` keyword arg (see how this is done for the "GCP Logs" nav item.)  (Could be improved by using a decorator instead.)

Either way, the nav items will then be hidden if the corresponding page is inaccessible.

**Comment by matkaczmarek** [comment]
> 
> This is where I disagree. I'd say just put them in! Add them to the nav menu in a place that makes sense.
> 

Sure! So, I will create a PR containing custom HDN admin panel tabs resolving this issue.
