### ISSUE TITLE
(Non-JS) browsing of subdirectories from project page

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#232]
In https://alpha.physionet.org/content/crisdb/, there is a link
for each subdirectory ("e", "f", "m", "old") but these links
don't do anything without JavaScript.

**Comment by bemoody** [comment]
The 'browsable-files' branch should fix this, but has the same severe security issue (issue #233) as the existing code.

**Comment by bemoody** [comment]
I should probably mention that this code is also likely broken if
the subdirectory requires URL encoding or HTML encoding.

We probably want to forbid users from creating such directories
(e.g., with spaces, ampersands, semicolons, apostrophes, quotes,
less-than or greater-than signs), but the code should be designed
to do the right thing anyway.

(The current code is, I assume, already broken for the cases of
quote, apostrophe, ampersand, less-than, greater-than, and/or
backslash.  I assume that there's some way to do the requisite
escaping in Django templates, but I haven't read that far just
yet. :P)

**Comment by elfeto** [comment]
As for now we only allow for folder creating or files the following syntax: letters, numbers, dashes, underscores, and dots. They may not contain adjacent dots, begin with, or end with a dot.

As for the 'browsable-files', I am allowing Nginx to index the published projects
https://alpha.physionet.org/static/published-projects/crisdb/files/
