### ISSUE TITLE
LightWAVE for public databases

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#244]
For public databases, we need:

 * A WFDB-compatible directory structure (issue #242)

 * A 'DBS' file

 * A 'wfdbcal' file

 * sandboxed-lightwave (CGI server) installed (issue #243) and
   accessible at a public URL

 * LightWAVE client (HTML/JS/CSS) installed and pointing to the
   correct server URL

**Comment by tompollard** [comment]
Implemented in https://github.com/MIT-LCP/physionet-build/pull/417
