### ISSUE TITLE
Add cite button to published projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#251]
Add prominent "cite" button to published projects that offers a quick way to get the citation for the project in common citation formats.

**Comment by alistairewj** [comment]
Google scholar is awesome

![image](https://user-images.githubusercontent.com/1282676/54058627-68410d80-41c4-11e9-90b8-3545929989ac.png)

**Comment by tompollard** [comment]
Looks like this overlaps with https://github.com/MIT-LCP/physionet-build/issues/688
