### ISSUE TITLE
Invited authors should be prompted to add their affiliation

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#258]
- Alistair created a new project and invited me to co-author. I responded to the email (copied below) to confirm that I was co-author. 
- Although I thought I'd completed the necessary steps for Alistair to continue, it turns out that the system is still awaiting my affiliation.
- The system needs to prompt the collaborating author to add their affiliation. The prompt should appear both in the email and in the submission system itself.

> Project title: The MIMIC-III Clinical Database
> Submission ID: oD9BokQBkal3KTTPqxWA
> Submitting author: alistairewj --- alistairewj@gmail.com
> 
> Dear Colleague,
> 
> You have been invited by Alistair Johnson (alistairewj@gmail.com) to co-author a project entitled "The MIMIC-III Clinical Database" on alpha.physionet.org. Please accept or decline this request as appropriate.
> 
> If you already have a alpha.physionet.org account, you may respond from your project home page:  http://alpha.physionet.org/projects/. If this email address is not associated with your account, you may add it from your email settings page or ask your co-author to resend their invitation to an alternative address.
> 
> If you do not have an account, please register here: http://alpha.physionet.org/register/. Once you have registered, you will find the pending invitation on your project home page.
> 
> Regards,
> 
> The PhysioNet Team,
> MIT Laboratory for Computational Physiology,
> Institute for Medical Engineering and Science,
> 45 Carleton St, Cambridge, MA 02142

**Comment by tompollard** [comment]
@jraffa @alistairewj @bemoody if you have suggestions for improving the way affiliations are handled (especially for collaborating authors), it would be great to have your thoughts.

Summary of current functionality:

- PhysioNet users have an optional affiliation associated with their profile (added at: https://alpha.physionet.org/settings/profile/). This affiliation is displayed on the public profile if it exists. The profile affiliation is **independent** of any project affiliation.
- Authors are required to add up to 3 affiliations on the project authors page (e.g.: https://alpha.physionet.org/projects/PROJECTID/authors/. 

Questions:

- Should the project affiliations be added independently of the profile affiliation? Or should they be combined in some way? 
- How should an author be prompted to add their affiliation when they are invited as a co-author on a project?

**Comment by jraffa** [comment]
I don't see harm in defaulting to profile affiliation, keeping track of the ones which have been explicitly approved, and a subtle nag like google scholar has about claiming/updating your articles but for unapproved affiliations/other material.

**Comment by tompollard** [comment]
Thanks Jesse. Felipe added a couple of changes in https://github.com/MIT-LCP/physionet-build/pull/268 to explicitly request the affiliation, which should make things clearer. Defaulting to the profile affiliation is probably a good idea too.

**Comment by alistairewj** [comment]
Definitely auto-importing the affiliation makes sense. A form of
autocomplete would be great to prevent affiliations for the same
institution varying e.g. MIT vs. Massachusetts Institute of Technology.
Obviously that's non trivial so another option could be a policy page e.g.:
https://jmir.zendesk.com/hc/en-us/articles/115001431711-How-should-I-enter-author-affiliations-

**Comment by tompollard** [comment]
Thanks, and good point about the autocomplete for affiliations. They are getting pretty messy at the moment (in a single project, we have someone as "MIT", someone as "Massachusetts Institute of Technology", and someone as "Massachusetts Institute of Technology, MA, USA")
