### ISSUE TITLE
Write internal editorial guidelines in admin console

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#261]
Write down the a standard set of steps to go through when reviewing a database. ie.

- Check description makes sense
- Signals:
  - Check sig names make sense
  - Check signal ranges
  - Check resolution
  - Make sure all headers and signals are readable
  - Inspect some waveform shapes

**Comment by tompollard** [comment]
Good idea. Not sure how you were thinking about organizing this, but it might be nice to collect documentation/guidelines together into a set of pages under an item in the console menu. e.g. 

```
- Users
- News
- Usage Stats
- Guidelines
    - Editorial Review
    - Credentialing
    - etc...
```

**Comment by cx1111** [comment]
That's exactly it

**Comment by tompollard** [comment]
Closing the issue now that we have a skeleton. This will be an ongoing task...
