### ISSUE TITLE
Project invitation emails not delivered to RGM

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#262]
RGM was invited to join two projects: "MIMIC-CXR" and "The eICU Collaborative Research Database", but there was no sign of the invitation emails in his inbox, quarantine filter, junk mail, etc. All other co-authors received the emails (Omar, Jesse, Leo, etc). An example of the invitation email is below. It would be good to track down what happened to the emails. Were they sent? If so, where did they end up?

```
From: PhysioNet Automated System [noreply@alpha.physionet.org]
Sent: Tuesday, March 12, 2019 4:05 PM
To: Jesse D Raffa
Subject: Invitation to author project: The eICU Collaborative Research Database

Project title: The eICU Collaborative Research Database
Submission ID: 29TC20aMKq2zcGt4SKhR
Submitting author: tompollard

Dear Colleague,

You have been invited by Tom Pollard to co-author a project entitled "The eICU Collaborative Research Database" on alpha.physionet.org. Please accept or decline this request as appropriate.

If you already have a alpha.physionet.org account, you may respond from your project home page: http://alpha.physionet.org/projects/. If this email address is not associated with your account, you may add it from your email settings page or ask your co-author to resend their invitation to an alternative address.

If you do not have an account, please register here: http://alpha.physionet.org/register/. Once you have registered, you will find the pending invitation on your project home page.

Regards,

The PhysioNet Team,
MIT Laboratory for Computational Physiology,
Institute for Medical Engineering and Science,
45 Carleton St, Cambridge, MA 02142
```

**Comment by elfeto** [comment]
There have been a lot of emails sent to "RGM" over the past couple of days, and in the log in the mauil server they were all successfully sent. Once a email is sent from our servers, they are out of my reach.
 
Mar 13 22:19:52 ***** postfix/smtp[16467]: 8A7499FB37: to=<*****@*****>, relay=mit-edu.mail.protection.outlook.com[104.47.40.36]:25, delay=2.4, delays=0.42/0.05/0.59/1.3, dsn=2.6.0, status=sent (250 2.6.0 <55cff949.545f.16979fb0702.Coremail.cangnaizhu327@163.com> [InternalId=20143396620228, Hostname=SN2PR01MB2013.prod.exchangelabs.com] 2396655 bytes in 0.439, 5330.374 KB/sec Queued mail for delivery)

The email should be in his spam or "Quarantine page".

This is a example of how it looks once a email is sent to a MIT email address.
If you are interested in following up in this issue,  contact the MIT IS&T.

**Comment by tompollard** [comment]
Thanks for checking! I'll follow up with IS&T.
