### ISSUE TITLE
Deceptive files in demo data

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#270]
In /demo-files/static/published-projects/kadzWaIVz0DQd72mL1cm/ is what appears to be a collection of random source files from some version of the WFDB Software Package, an incorrect license, and a zip file called "wfdb-10.5.24.zip".

Please remove these files.

If you want to use WFDB as an example, that would be fine - but in that case, please use the *actual* WFDB package for that purpose.  It's not as if the actual package is hard to find.

**Comment by tompollard** [comment]
This is a test fixture, I assume? These are only used in development and may have intentional problems to allow testing. Agree that it makes sense to switch anything out that might be misleading.
