### ISSUE TITLE
Front page content

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#272]
Before switching to the new site, we need to reach agreement on the content of the front page (https://alpha.physionet.org/). In our last catch-up, it was suggested that the page needed to be changed to focus more on resource discovery. The simplest option would be to reproduce the current site (https://physionet.org/) for now, but it would be good to use this opportunity to rework things a little.

**Comment by lbulgarelli** [comment]
I've been looking at new layout options for the home page.

This is what I came up with so far:

<img width="1680" alt="Screen Shot 2019-03-18 at 10 24 53 AM" src="https://user-images.githubusercontent.com/17076959/54537068-3cfab300-4968-11e9-905e-010eae227065.png">

I created the branch 'home' for the changes, at: https://github.com/MIT-LCP/physionet-build/tree/home

Let me know what you think.

**Comment by elfeto** [comment]
The sidebar could be retractable. (like the admin console)

**Comment by tompollard** [comment]
After discussion with Ary and Madalena, the current version is:

![Screen Shot 2019-04-16 at 10 46 33](https://user-images.githubusercontent.com/822601/56219562-f5ce1380-6034-11e9-9819-eddeea6d6967.png)

**Comment by alistairewj** [comment]
Could use a bigger ECG to break up the background e.g. 

![image](https://user-images.githubusercontent.com/1282676/56219758-4b0a2500-6035-11e9-9044-38572d30558a.png)

**Comment by tompollard** [comment]
Current version (thanks Lucas!):

![Screen Shot 2019-04-16 at 21 30 20](https://user-images.githubusercontent.com/822601/56254467-e24f9680-608e-11e9-8fa0-8db1b87e2e17.png)
