### ISSUE TITLE
Migration of PhysioNetWorks projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#273]
PhysioNetWorks projects will need to be migrated (https://physionet.org/works/). These projects are "in progress" and should eventually be made publicly available:

![Screen Shot 2019-03-15 at 16 43 54](https://user-images.githubusercontent.com/822601/54461043-cd0ae380-4741-11e9-8a34-36fec5f98037.png)

There is a fair amount of variation between projects (e.g. quality of content, number of collaborators, activity), so our approach for migration will vary by project.

Outline of the current workflow:

![Screen Shot 2019-03-15 at 16 43 35](https://user-images.githubusercontent.com/822601/54461048-d300c480-4741-11e9-81cf-afe478d529d0.png)

**Comment by peterhcharlton** [comment]
Thanks for this Tom.

I currently have a couple of PhysioNetWorks projects which (in the next few weeks) I would like to request a review of for public posting.

To request review, should I:
1) make a copy of the project on alpha.physionet.org, uploading the project blurb and data again,
2) wait until the project is migrated onto alpha.physionet.org, or
3) something else?

Many thanks,

Pete

**Comment by tompollard** [comment]
Hi Pete, hope all is well and thanks for asking! If you don't mind, it would be helpful if you could submit via alpha.physionet.org. 

The system is currently in testing, so we would love your feedback on the process. In particular, we would welcome your thoughts on (1) things that you like (2) how the new site compares to the current site (3) specific things that need improving.

You could add feedback to this thread, raise new issues for individual bugs that need fixing, and/or send us an email.

**Comment by peterhcharlton** [comment]
Great, thanks Tom. I'll submit them on alpha.physionet.org. Happy to pass on feedback

Pete

**Comment by tompollard** [comment]
Thanks Pete! Give us a shout if you run into any issues.
