### ISSUE TITLE
Search button does nothing without JS

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#284]
Search button leads to a page that says

    Use this page to perform a google custom search on this
    site. You may also use the topic keyword search.

and is otherwise blank.

**Comment by tompollard** [comment]
I think Lucas is going to look at improving the search (ideally moving away from using the Google search). We have the same issue with the current PhysioNet site.

<img width="718" alt="Screen Shot 2019-03-18 at 21 23 23" src="https://user-images.githubusercontent.com/822601/54573801-22eebe00-49c4-11e9-8280-0d8d8f0f7e6e.png">

**Comment by bemoody** [comment]
Not so, have you tried it?

    <noscript>
    <form action='https://www.google.com/search'>
      <div>
        <input name='q' type='hidden' value='site:physionet.org' />
        <input name='q' size='25' type='text' />
        <input name='sa' type='submit' value='Search' />
      </div>
    </form>
    </noscript>

Enter "mitdb" and you get:

https://www.google.com/search?q=site%3Aphysionet.org&q=mitdb&sa=Search

**Comment by tompollard** [comment]
The screenshot above is from the current site.

**Comment by cx1111** [comment]
@bemoody can you tell me why we need to make the whole site work without js? We're making our code open.

- lightwave requires js
- edit: navbar been updated
- gmail requires js. You can pull content into your mail client but you need js to sign up
- all video streaming sites require js
- MIT Athena requires js for Duo
- Amazon web services requires js
- Google cloud platform requires js
- If you want any number of dynamic forms, ie filling in references, without js, you'd have to preload the max number of forms (20) which would be even more messy/confusing.

Also the alpha site is lacking A LOT of functionality which we need to build. Is focusing on lack of non-js functionality the correct priority right now?

**Comment by cx1111** [comment]
Regarding this topic, the bigger issue is that the search doesn't work because we're not allowing google to index the site.

**Comment by bemoody** [comment]
On 3/19/19, Tom Pollard <notifications@github.com> wrote:
> The screenshot above is from the current site.

Sorry for the silly question.  And yes, that could be improved.  But
where, if anywhere, did you find a link pointing to
/search-results.shtml ?  If you're using a non-javascript browser, you
would not normally ever see that page.

**Comment by tompollard** [comment]
It's on the front page of the site (https://physionet.org/), at the top right.

**Comment by bemoody** [comment]
On 3/19/19, Tom Pollard <notifications@github.com> wrote:
> It's on the front page of the site (https://physionet.org/).

It is *not*.  It's only there in a document.write block:

    $ curl https://physionet.org/ 2>/dev/null | grep -C3 search-results

          <div style="float: right; padding: 0.6em; margin: 0;" id="searchForm">
            <script>
    document.write("<form action=\"/search-results.shtml\"> " +
                   "<input type=\"text\" name=\"q\" size=\"25\" /> " +
                   "<input type=\"submit\" name=\"sa\" value=\"Search\" /> " +
                   "</form>");

If you open the page in a non-javascript browser, all you will see is
the plain form, which submits to <https://www.google.com/search>.

**Comment by tompollard** [comment]
Gotcha, so the issue was that I was already on the page when I switched off javascript.

**Comment by tompollard** [comment]
@bemoody search was updated in #331 and #318 (plus others) and should no longer require javascript. are you happy that this issue is now resolved?

**Comment by bemoody** [comment]
Cool!
