### ISSUE TITLE
Navigation when menu is invisible

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#287]
When window is narrower than about 768 pixels, the menu bar items become completely invisible except for the "PhysioNet" in the corner.

TBH, this seems just fine to me; we just need then to ensure that all of the links in the menu bar are also accessible via "normal" links from the front page.

(For example, /about/ is linked from the main page and /about/timeline/ is linked from /about/, but /about/contact/ does not seem to be accessible.)

**Comment by tompollard** [comment]
I like the navigation bar that Zenodo have in their footer. We could consider something like that: https://zenodo.org/.

**Comment by bemoody** [comment]
You're talking about the mini site-map with "About", "Policies",
"Infrastructure" etc.?  I agree that looks nice and better than a
drop-down menu bar in general.

Might not want that much stuff at the bottom of every page, although
it helps that they've used contrasting colors to set it apart from the
main page body.

**Comment by tompollard** [comment]
Yep, that's the bit I'm talking about. If you'd like to have links to pages outside the menubar, then that might be a nice way of implementing it.

**Comment by tompollard** [comment]
Lucas added [a menu icon](https://www.w3schools.com/howto/howto_css_menu_icon.asp) in #293 and #304 to support navigation on narrow screens, which I think addresses this issue. Please reopen if you think not.
