### ISSUE TITLE
Project upload page very broken with narrow window

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#290]
"Narrow" is a bit of an exaggeration.  If the window is less than about 989 pixels in width (I guess when the five large buttons don't all fit on one line?), the latter three buttons move to the side and crush the file display into unreadability.

It looks something like this:

    [Upload Files] [Create Folder]
       Folde    [Rename Item] [Move Items] [Delete Items]
    r
    Navigati
    on:
    <base>
    Na  S
    me  i
        z
    M   e
    o
    d
    i
    f
    i
    e
    d

**Comment by tompollard** [comment]
I can't point to the exact commit without doing some digging (possibly https://github.com/MIT-LCP/physionet-build/pull/337?), but I believe this was dealt with by Lucas. Please could you take a look at https://alpha.physionet.org/ and close the issue if you're okay with the fix?

**Comment by bemoody** [comment]
No, this issue was about the file upload page, which is not fixed.
The problem appears to be with project_files_form.html and/or
edit_files_panel.html.  At a minimum there should be something to
"clear" after the "float", but the button layout itself could be
better...

    [Upload Files] [Create Folder]
                       [Rename Item] [Move Items] [Delete Items]

...feels unnatural to me (even apart from the lack of vertical
padding.)  Could it be tweaked so that the latter three buttons *only*
float right if there's enough space to fit them on one line, and
otherwise all the buttons are left-aligned?

Also, I'm not sure why the info for each file needs to be broken onto
3 lines (name, size, date) while there is plenty of white space off to
the right, and a checkbox sitting forlornly in the middle of the page.

**Comment by bemoody** [comment]
Maybe *center* all the buttons?

    <div1>
      <button1>
      <button2>
      <div2>
        <button3>
        <button4>
        <button5>
      </div2>
    </div1>

* if page is wider than X, div1 has text-align:left and div2 has float:right

* otherwise, div1 has text-align:center

I don't know, just an idea.  Anyway, the buttons still need vertical padding.
