### ISSUE TITLE
[Suggestion]: Return button on preview page

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#291]
The preview page doesn't have a direct link back to the project (as far as I am aware) - you have to go My Projects -> Find the Project -> Click. Seems like a common workflow would be Preview project -> Back to project -> Preview -> Back to project etc so a button would be useful.

**Comment by alistairewj** [comment]
After discussion with @elfeto I think probably adding the text "Opens in new window" next to the preview button is the best fix since at the time it wasn't clear to me that it would open in a new window.

**Comment by tompollard** [comment]
Thanks, looks like there is W3C guidance for this: https://www.w3.org/TR/WCAG20-TECHS/G201.html.

> G201: Giving users advanced warning when opening a new window
> Opening new windows automatically when a link is activated can be disorienting for people who have difficulty perceiving visual content, and for some people with cognitive disabilities, if they are not warned in advance. Providing a warning allows the user to decide it they want to leave the current window, and the warning will help them find their way back, if they do decide they would like to go to the new window. It will help them understand that the "back" button will not work and that they have to return to the last window they had open, in order to find their previous location.

The webpage suggests two methods for warning the user (HTML text and CSS). We'll add a fix!
