### ISSUE TITLE
Allow corresponding author to set other affiliations

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#292]
It would probably be nice to save the editor work on cleaning up author affiliations. I think the corresponding author should be able to update the affiliations of contributing authors before submitting. Some ideas on what could be implemented:

1. When inviting a new author, the corresponding author must set their affiliation (courtesy of @tompollard)
2. Allow invited author to set their affiliation on invite acceptance, then only allow corresponding author to update it later
3. Allow both invited author/corresponding author to update it at any time
4. Leave the system as it is and let the editor clean it up project by project

**Comment by elfeto** [comment]
If the Person registered in PN has a Affiliation in their profile, the affiliation will be carried over. No questions asked.
option 2 is really messy.
option 3 probably is not that hard.
option 4 would be to on acceptance set affiliations to "NONE", and let the editor suffer.

I vote for 4 or 3...

**Comment by elfeto** [comment]
Do we still want this? 
Now once a author accepts a invitation, if he has a affiliation in his profile, it will be automatically added, and if he doesn't, he will be forwarded to the page in which he sets them.

**Comment by tompollard** [comment]
I think this can be closed for now. Hopefully the improvements address the core issue. If not, we can reopen or raise a new issue.
