### ISSUE TITLE
Not clear that authors need to approve final version before publication

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#295]
Once the project has been copyedited, all authors receive an email to say the project has been accepted. It is not clear from this email that to proceed with the process every author needs to approve the project for publication. We should either: 

1. clarify that all authors need to approve the project, or
2. allow the submitting author to approve the project on behalf of all authors.

> Project title: TITLE
> Submission ID: ID
> Submitting author: NAME
> 
> Dear NAME,
> 
> Based on the recommendations of our editors, we are delighted to accept your project entitled "PROJECT TITLE" for publication on PhysioNet. 
> 
> A summary of our standard set of editorial checks is listed below:
> - Has the data been produced in a sound manner?: Yes
> - Is the data adequately described?: Yes
> - Is the data provided in an open format?: Yes
> - Are the data files machine-readable?: Yes
> - Does the project include everything needed for reuse by the community?: Yes
> - Is the data free of protected health information?: Yes
> - Is the content suitable for PhysioNet?: Yes
> 
> Additional comments from the editorial team are listed below:
> COMMENT.
> 
> After copyediting of the project and files is complete, we will be in touch again. Then, once all authors approve of the copyedited version at: http://THEURL, the project will be ready for publication. 
> 
> Regards,
> 
> The PhysioNet Team,
> MIT Laboratory for Computational Physiology,
> Institute for Medical Engineering and Science,
> 45 Carleton St, Cambridge, MA 02142

Any preference for 1 or 2? Remember that by this point, all authors have already approved the initial submission.

**Comment by elfeto** [comment]
That email that you show there, is before the copy edit phase. 

After the copyedit they receive this email:
In which I think is a bit clear that if they are a author, they have to approve the submission.

> Project title: TITLE
> Submission ID: ID
> Submitting author: NAME
> 
> Dear NAME,
> 
> We are pleased to say that copyediting of your project entitled "PROJECT TITLE" is now complete. We were satisfied with the state of your project and no changes were made.
> 
> When all authors have approved this version of the project using the online system, it will be ready for publication on PhysioNet.
> 
> Regards,
> 
> The PhysioNet Team,
> MIT Laboratory for Computational Physiology,
> Institute for Medical Engineering and Science,
> 45 Carleton St, Cambridge, MA 02142

We can make this even more obvious tho...

**Comment by tompollard** [comment]
Thanks Felipe, didn't spot this email.  This is clearer, but we could definitely make more obvious (e.g. with a direct request at the start of the email and a link). I'll take a look later if someone doesn't get there before me...
