### ISSUE TITLE
Facilitate downloading all files in a database

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#309]
Right now there are two methods of downloading files:

* manually download each file
* (if the zip is present) click the `Download zip` file next to the file list

The zip file for each project is generated by the editor, so for some projects it doesn't exist, e.g. https://alpha.physionet.org/content/ecgcipa/
This may be intentional to save disk space.

Ideally we would push bulk downloads to GCP, so this issue is a reminder to add a command to each published database which details how to rsync/curl/wget the data.

**Comment by tompollard** [comment]
Thanks to Felipe, admin users can opt to send a project to the Google Cloud (https://github.com/MIT-LCP/physionet-build/pull/352). When a data is available on the cloud, options for downloading and accessing the files are displayed on the project page. We could add command line suggestions for working with the files (and/or perhaps build this into a PhysioNet package).

**Comment by bemoody** [comment]
When you say "options for downloading and accessing the files are
displayed on the project page", where is this information shown
exactly?

**Comment by elfeto** [comment]
So, I checked and every published project (NOT software) have the zip, and are in GCP.

What I believe @tompollard says is that there will be a button to download from GCP, a link in which one can browse using GCP, and another button to download the zip form the server.

This will always rely on the editor that publishes the content. So, I think we should close this, unless @alistairewj  is unsatisfied with the answer.

**Comment by elfeto** [comment]
In #537  you can download files from open projects using:

**wget -r -np -nd -P <location_to_store_the_files> <URL>**
