### ISSUE TITLE
Unable to upload empty files ("The submitted file is empty")

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#317]
The files page in the submission system blocks the user from uploading empty files and displays a "the submitted file is empty" message. 

There are times when people may intentionally include an empty file in a project (for example `__init__.py` for Python packages), so we should review this restriction.

**Comment by bemoody** [comment]
Could we change the error to a warning message, shown at the top of
the page, but not preventing the upload?

Also - if you try to upload several files at once and one of them is
empty, what happens to the others?

**Comment by elfeto** [comment]
We can allow empty files if you want, also the files would be discarded and not uploaded.

**Comment by tompollard** [comment]
> Could we change the error to a warning message, shown at the top of the page, but not preventing the upload?

This sounds good to me...though I wouldn't be against removing the warning altogether, especially when thinking about your second point...

> Also - if you try to upload several files at once and one of them is empty, what happens to the others?

Um, I just uploaded an empty file by including it alongside a collection of non-empty files!
