### ISSUE TITLE
Automatic vs. manual "short description"

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#321]
A minor issue I noticed in pull request #319 is the way the code automatically truncates the abstract to generate a short description.

Properly handling HTML tags is certainly important, so thank you, Lucas, for spotting and fixing that.

But apart from that, I think that simply cutting the abstract off at 250 characters is not a great idea as it will not necessarily lead to something readable.

One alternative would be to *require* that the author or editor supply a short description in every case (which could, perhaps, be automatically filled in with the first sentence or so of the abstract.)  I don't know, is this something that is already done?  Or something that could easily be done going forward for newly-submitted projects?

**Comment by tompollard** [comment]
Yep, it was a good spot by Lucas! I'd be happy with making short_description a required field. This should be straightforward to implement and it is a simple field for authors to provide.
