### ISSUE TITLE
Reverse order of submission timeline

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#351]
At the moment the project submission page lists the timeline in chronological order top to bottom - but I think it makes more sense to present the information in reverse chronological order, with the most recent event at the top of the page. This is especially nice if the project is awaiting approval, as the approval button will be at the top of the page.

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/387
