### ISSUE TITLE
PhysioNet domain redirects and 404s

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#360]
Finish the tasks in the 'in progress' tasks in project 1: https://github.com/MIT-LCP/physionet-build/projects/1
 
Once that is done, make physionet.org point to the new site, and archive.physionet.org point to the current site.

Change the ssl certificates and proxies.

Add a url and view to catch links that don't exist on the new site, showing a 404 that suggests they go to the archive site.

**Comment by tompollard** [comment]
We have switched to the new site and 404s are redirecting to https://archive.physionet.org/.
