### ISSUE TITLE
no new news on published content

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#363]
When something is pushed there should be a automatic news article.

**Comment by cx1111** [comment]
Isn't that just redundant and a waste of space? The reason why we have news items for them now is that the front page doesn't have the functionality to show latest published items.

**Comment by tompollard** [comment]
Felipe, just to check I understand, are you suggesting that publication of a project should trigger the creation of a news item? If so, I kind of agree with Chen that this will mean a lot of duplicate content. 
Might be good to trigger other actions though - e.g. creation of a post on a social media account.
