### ISSUE TITLE
Character limit for response to editorial review is too small

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#374]
I'm reviewing a project and just received an e-mail from the author prefaced with:

> The feedback on the new platform restricts the reply to 500 characters which is limited. Hence I am emailing you the in-line response to each suggestion:

I'd definitely agree that 500 characters is not enough. Can we make this field `TEXT` and allow arbitrary length response to editorial review?

**Comment by tompollard** [comment]
Agree, this needs fixing!

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/387. Word limit increased to 12000 characters.
