### ISSUE TITLE
Search results page problems

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#379]
1. The search results page begins by stating

"This page contains all of the databases, software and challenges
published on PhysioNet."

This statement is quite deceptive.  If you don't perform a search
(i.e. you just go to https://alpha.physionet.org/content/) then you
will see a page containing the ten most recently released projects,
which is a long way from "all".

If you *do* perform a search, then you will only see the resources
that matched your query, which is also nothing like "all".

2. If viewing the page in a window that is not very large (> 1000
pixels), the *entire visible page* consists of form fields.  When I
load the page, at least half of what I see should be actual content.

**Comment by tompollard** [comment]
> This statement is quite deceptive. If you don't perform a search (i.e. you just go to https://alpha.physionet.org/content/) then you will see a page containing the ten most recently released projects, which is a long way from "all".

You are seeing a list of all projects, but there is a paging bar to avoid displaying an incredibly big page.

![Screen Shot 2019-04-16 at 14 29 40](https://user-images.githubusercontent.com/822601/56234814-16f22c80-6054-11e9-855b-5bb338f2b839.png)

**Comment by tompollard** [comment]
The statement was removed.
