### ISSUE TITLE
News titles limited to 40 characters

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#414]
40 characters seems rather short for the maximum length of a news item title (see the one that Tom just posted...)

Also, does the form not complain if the user tries to enter something longer than the maximum?

**Comment by tompollard** [comment]
> 40 characters seems rather short for the maximum length of a news item title (see the one that Tom just posted...)

I agree we should increase the length.

> Also, does the form not complain if the user tries to enter something longer than the maximum?

Not currently, but it would be nice if it did!
