### ISSUE TITLE
Order of author list is not conserved in project lists and suggested citation

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#419]
The original order of authors should be retained wherever the list appears (for example, when projects are listed in search results and in the suggested citation that appears at the top of projects).

**Comment by bemoody** [comment]
That's not good...

It looks like project authors have a 'display_order' field.  Is that
the order we should be using?  Is that field not being set correctly
in the database, or are views not correctly sorting the list based on
that field?

**Comment by tompollard** [comment]
Haven't looked into the details yet, but pretty sure it's just a rendering issue.

**Comment by tompollard** [comment]
(sorry, and yes, the "display_order" should be used for the sort)

**Comment by bemoody** [comment]
On the database side, shouldn't we have unique_together
('project','display_order') ?

<https://docs.djangoproject.com/en/2.2/ref/models/options/#unique-together>

**Comment by tompollard** [comment]
To ensure that the display order is unique for a given project? Probably, yes! I was just thinking about something similar...we dodged several issues around authorship for simplicity, one of which is shared authorship (e.g. equal contribution of first-authors). See @alistairewj's issue at: https://github.com/MIT-LCP/physionet-build/issues/369

We should think about how we want to handle this. It might be that the display order is still unique, but we have a flag to indicate equal contribution (then display an icon alongside equal contributors when displaying the author list).
