### ISSUE TITLE
Improve the submission form for derived projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#421]
The submission form for derived projects (displayed at `/projects/slug/discovery`) could be improved:

![Screen Shot 2019-04-25 at 17 21 41](https://user-images.githubusercontent.com/822601/56769259-ad260100-677e-11e9-988f-74d50f672bcc.png)

The current form takes up a fair amount of space and may be tricky to use when there are lots of projects to choose from.

**Comment by elfeto** [comment]
Done by Lucas in #486
