### ISSUE TITLE
Run lightwave tests as part of automated test suite

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#430]
The lightwave branch includes tests for the lightwave server, but these tests are skipped if the server isn't installed.   I assume it should be possible to add the server in 'shippable.yml' but I haven't tried.

**Comment by tompollard** [comment]
> I assume it should be possible to add the server in 'shippable.yml' but I haven't tried.

Essentially shippable just uses the yaml file as a set of instructions for building the testing server, so this should be possible. (e.g. wget the packages, compile, add symlinks if needed, then start the server).
