### ISSUE TITLE
Tracking of migrations

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#444]
Database migrations need to be tracked somewhere.  We need to be sure that

- we have a way to review and test django's auto-generated migrations before applying them to the live server

- we have a way to make manual migrations if necessary

- staging server uses the same migrations as the live server

We talked about this but I'm not sure we ever did anything about it.  I, for one, still have no idea how to safely deploy changes that require a migration.

**Comment by elfeto** [comment]
Well see how this goes after #465

**Comment by bemoody** [comment]
Should be fixed with pull request #479 (but let's see how well it works and make further adjustments if needed.)
