### ISSUE TITLE
Improve user interface for adding derived projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#452]
@lbulgarelli, as discussed it would be good to replace the list of items at https://alpha.physionet.org/projects/SLUG/discovery/ with a search tool:

![Screen Shot 2019-05-02 at 15 37 42](https://user-images.githubusercontent.com/822601/57101980-6e4cf980-6cf0-11e9-9676-feec0119da83.png)

**Comment by elfeto** [comment]
Thanks @lbulgarelli
