### ISSUE TITLE
Old projects with "The" in the title

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#495]
It really bothers me that several (old) projects have titles beginning with "The":

* "The De-Identification Software Package"
* "The eICU Collaborative Research Database"
* "The EVAL_ST Tool" (description also lacks markup)
* "The MIMIC-III Clinical Database"
* "The MIMIC-III Clinical Database Demo"
* "The Non-Invasive Fetal ECG Arrhythmia Database"
* "The WFDB SWIG Toolbox for MATLAB"

**Comment by tompollard** [comment]
Options to consider are:

1) remove "The" from the titles and have a clear policy on titles for future submissions. Not ideal to be changing titles, but I think it's okay at this stage given we are still in development stage.
2) work out why it's annoying to have titles starting with "The" (e.g. sorting by title is unsatisfactory) and then deal with these issues independently.

**Comment by bemoody** [comment]
Yeah, sorting is the big issue, but also just stylistic consistency.
I realize these were the actual <title>s of many of the old HTML
pages, but seeing them in a list together with other project titles
makes them more jarring.

**Comment by tompollard** [comment]
Technically it should be possible to update the titles using the admin tool (e.g. https://staging.physionet.org/content/mimiciii/1.4/). We'll need to think about downstream issues that will need fixing (e.g. updating archived metadata).

**Comment by tompollard** [comment]
Titles of the projects mentioned in your original post have been updated. We should also make a note of the policy somewhere in our project guidelines.

**Comment by tompollard** [comment]
Updating guidelines is covered in https://github.com/MIT-LCP/physionet-build/issues/448, so I think this issue is dealt with.
