### ISSUE TITLE
HTML file previews

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#504]
I'd like to have an HTML preview for project files.

For example:
 - CSV files formatted as a table
 - Source files with syntax highlighting
 - Binary data files with a summary of the format
 - Summary of headers from .edf, .mat, .wav

I see this as being something useful both for visitors and for editors, and also as a way of making our data format requirements clearer for authors.

I've done some preliminary work on this, but what I'm not sure about is what the URLs ought to look like.  We'd have two or three different URLs for each file:
 - one to show an HTML preview
 - one to view the file itself as plain text
 - possibly a third which would have the same content as the second, but would also force browsers to download the file (see also issue #310.)

My first thought was that these should have the same path and different query strings (`/content/foo/1.0/bar.c` for the HTML view, `/content/foo/1.0/bar.c?plain` for plain text, `/content/foo/1.0/bar.c?download` to force download).  But that would cause wget to save the file as `bar.c?plain` (and save the HTML as `bar.c`), plus there's no easy and obvious way to recursively wget just the plain files.

My second thought was that we could serve a different default version based on the 'Accept' header, so web browsers would see the HTML version, while wget/curl/wfdb/etc. would see the plain file.  (This is a terrible idea.  I'm just putting it out there so I can point out what a terrible idea it is.)

So what I'm thinking now is to have two separate paths, e.g. `/content/foo/1.0/bar.c` for the HTML view and `/content/foo/raw/1.0/bar.c` for the plain file.  This is how several popular VCS browsers do it.  (It still bugs me a little that wget will save the HTML file as `bar.c` in this case.  Probably this is not a huge concern, but it is slightly at odds with what *PhysioNet* users expect.  One option might be to add either a trailing slash, or a `.html` suffix.)

So here are a few options.  For the HTML version:
 - `/content/foo/view/1.0/bar.c`
 - `/content/foo/1.0/bar.c`
 - `/content/foo/1.0/bar.c?view`
 - `/content/foo/1.0/bar.c/`
 - `/content/foo/1.0/bar.c.html`

For the plain version:
 - `/content/foo/raw/1.0/bar.c`
 - `/content/foo/1.0/bar.c`
 - `/content/foo/1.0/bar.c?raw`

For the force-download version:
 - `/content/foo/raw/1.0/bar.c?download`
 - `/content/foo/download/1.0/bar.c`
 - `/content/foo/1.0/bar.c?download`

Bearing in mind that the HTML version is the version that people will typically want to *link to from a web page*, and the plain version is the version that people will want to use *programmatically*, which of the above seems least ugly to you folks?  Or are there any other possibilities I haven't mentioned?

**Comment by bemoody** [comment]
For what it's worth, here's how a few different VCS browsers do it:
 * cgit
    - Directory listing: `.../tree/foo`
    - File preview: `.../tree/foo/bar.c`
    - Plain file: `.../plain/foo/bar.c`
    - No link to force download
 * gitlab
    - Directory listing: `.../tree/1.0/foo`
    - File preview: `.../blob/1.0/foo/bar.c`
    - Plain file: `.../raw/1.0/foo/bar.c`
    - Force download: `.../raw/1.0/foo/bar.c?inline=false`
 * github
    - Directory listing: `.../tree/1.0/foo`
    - File preview: `.../blob/1.0/foo/bar.c`
    - Plain file: `.../raw/1.0/foo/bar.c`
    - No link to force download
 * viewvc
    - Directory listing: `.../foo/`
    - File preview: `.../foo/bar.c?view=markup`
    - Plain file: `.../*checkout*/foo/bar.c`
    - No link to force download

And here's the default behavior for a few user agents:
 * wget
    - `wget http://example.com/foo.c` saves as `foo.c`
    - `wget http://example.com/foo.c?blah` saves as `foo.c?blah`
    - `wget http://example.com/foo.c/` saves as `index.html`
    - `wget http://example.com/foo.c/?blah` saves as `index.html?blah`
 * curl
    - `curl -O http://example.com/foo.c` saves as `foo.c`
    - `curl -O http://example.com/foo.c?blah` saves as `foo.c?blah`
    - `curl -O http://example.com/foo.c/` chokes
    - `curl -O http://example.com/foo.c/?blah` saves as `?blah`
 * firefox
    - Visiting an HTML page and pressing Ctrl+S saves as `TITLE.html`
    - Right-clicking and saving a link to `http://example.com/foo.c` saves as `foo.c`
    - Right-clicking and saving a link to `http://example.com/foo.c?blah` saves as `foo.c`
    - Right-clicking and saving a link to `http://example.com/foo.c/` saves as `RANDOM-GARBAGE.html`
    - Right-clicking and saving a link to `http://example.com/foo.c/?blah` saves as `RANDOM-GARBAGE.html`
    - All of the above can be overridden by the Content-Disposition header

**Comment by bemoody** [comment]
I've uploaded my work to the 'view-files' branch.  It could be better organized and there are several things I'm not really happy with, so not opening a pull request yet; but you're welcome to try it out.

**Comment by tompollard** [comment]
It looks excellent. I like the URL structure that you ended up with. The only issue that I found is that something terrible happens if you visit: ```http://127.0.0.1:8000/content/PROJECTSLUG/raw/VERSION/```. e.g. don't go to: `http://127.0.0.1:8000/content/demobsn/raw/1.0/`
