### ISSUE TITLE
Credentialing form "suffix" auto filled with phone number?

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#529]
Apparently some browsers will try to fill in the "suffix" field with a phone number?  (I haven't seen this myself.  But it seems not out of the question since apparently some people refer to the "part of the phone number that doesn't include country or area code" as the "suffix".)

If we can replicate this problem, might be worth trying changing the name of the form field to "name_suffix" or something similarly less ambiguous.

**Comment by lbulgarelli** [comment]
Fixed on #551
