### ISSUE TITLE
Disable auto-filling in credentialing form?

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#530]
Might be worth setting autocomplete=off for credentialing form, because honestly, this isn't something you're going to be submitting often, and you *should* think carefully and be sure you're entering accurate information.

**Comment by tompollard** [comment]
I had a (quick!) look into this and I couldn't see a well-supported approach for switching off auto-complete for form fields. I think the main issue at the moment is on the original site...it seems that we're bouncing a lot of applications for phone numbers being listed in the suffix.

**Comment by bemoody** [comment]
Oh, there will never be any guarantees!  But there is a standard
('autocomplete' attribute) and it sounds to me like many browsers do
support it partially.  Assuming this is desirable, I don't see any
harm in setting the attribute.

**Comment by tompollard** [comment]
Setting the autocomplete attribute (`autocomplete="off"` or `autocomplete="new-password"`) seems worth trying (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion). 

Your suggestion of changing the field name in https://github.com/MIT-LCP/physionet-build/issues/529 also seems like it could work.

**Comment by lbulgarelli** [comment]
Fixed on #551
