### ISSUE TITLE
Integrate with the DataCite API for assigning DOIs to projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#538]
We now have an account on the DataCite DOI Fabrica test system (https://doi.test.datacite.org). This issue is a placeholder for integrating with the API to allow us to assign DOIs to published projects. 

> It is important to note that you are a “Provider” and you have a “Client”. Clients use Fabrica to create and manage DOIs and their associated metadata. Providers use Fabrica to administer Client accounts and activities related to DOI registration. 

> Test accounts have the same capabilities as production accounts, but none of the DOIs you create are permanent or resolvable. The same account credentials work for the test instance of DOI Fabrica and the test instances of our APIs:

> * REST API (https://api.test.datacite.org) 
> * MDS API (https://mds.test.datacite.org)
> * EZ API (https://ez.test.datacite.org)

> I encourage you to take a look at our Testing Guide (https://support.datacite.org/docs/testing-guide) for more information. 

Essentially there should be a step prior to publication that assigns a unique identifier to the project, then registers this DOI along with its associated metadata (see: https://support.datacite.org/docs/schema-v41). 

Instructions for creating DOIs via the REST API are at: https://support.datacite.org/docs/api-create-dois. Note that there are different DOI states - draft, registered, and findable. We probably want to create the draft first, then use the "publish" action to trigger a move from draft to findable.

> A word on states - publishing to findable
> In the previous examples you can see an "event" attribute added to our json payload, this corresponds to the action you want to trigger for the DOI.
In the case of reaching a findable state, we parse "publish" this pushes it through to the findable DOI state.

> Possible actions:

> publish - Triggers a state move from draft or registered to findable
> register - Triggers a state move from draft to registered
> hide - Triggers a state move from findable to registered

**Comment by elfeto** [comment]
Done in #855
