### ISSUE TITLE
Unable to assign slugs ending in -[0-9]

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#544]
It looks like there is a bug in the code to prevent ending on a hyphen when assigning a slug for a project. You can't input `test-123` even though it should be valid.

slug | valid
--- | ---
`test` | yes
`test123` | yes
`test-123` | no (bug)
`test-` | no (intentional)

**Comment by bemoody** [comment]
That's deliberate; we don't want 'test-123' as a project name because
it could be interpreted as version '123' of 'test'.

**Comment by alistairewj** [comment]
This eliminates project slugs like `embc-challenge-2018`, which was a bit unfortunate. Doesn't slug versioning append `v1`, `v2.0`, etc?

**Comment by bemoody** [comment]
Hmm.  We could require that all version numbers include a dot, and
avoid possible ambiguity that way.

(We've traditionally had databases labelled as "version 2", "version
3", etc. - but those were somewhat informal.  (There were at least two
different releases of "version 2" of the MIMIC II Waveform Database
and at least three releases of "version 3"; each release added new
records but didn't change the database structure.))

"wfdb-10.6.2" is standard practice; "wfdb-v10.6.2" looks hideous. :P

**Comment by alistairewj** [comment]
That's fair! I like the idea of requiring dots; we should push semantic versioning anyway. Seems like a good compromise.

**Comment by tompollard** [comment]
Currently the rule is "Version may only contain numbers and dots, and must begin and end with a number.", so we do kind of require semantic versioning. It is possible to list a single integer though (e.g. version "1"). So is the suggestion here to require at least one dot (e.g. "1.0") or at least two dots ("1.0.0")?

**Comment by alistairewj** [comment]
At least one dot seems the way to go since we've already adopted that for MIMIC, eICU, etc.
