### ISSUE TITLE
"Editor Response" form should include additional options (currently just yes/no)

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#546]
When reviewing a project, the editor is required to select Yes/No for a list of questions before selecting "Accept"; "Reject" or "Revisions accepted". e.g.:

- Has the data been produced in a sound manner? Yes/No
- Is the data adequately described? Yes/No
- Are the data files machine-readable? Yes/No
- Is the project free of protected health information? Yes/No
- Is the content suitable for PhysioNet? Yes/No

Sometimes the editor may want to select something like "More detail needed" or "To be confirmed" or similar, instead of yes or no. Reasons for this include:

-  To determine whether "the data been produced in a sound manner?" may require additional information.
- The editor may choose not to review data files until the authors have provided a detailed descriptive information, so the answer to "Are the data files machine-readable?" etc may be unclear.

**Comment by elfeto** [comment]
I think this was addressed right ?

**Comment by tompollard** [comment]
Yes, thanks - this was addressed, so the issue can be closed.
