### ISSUE TITLE
Nav bar search returns different results to the search page

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#548]
Searching for "MIMIC-III" using the search bar in the menu returns different results to the same search using the search tool at: https://alpha.physionet.org/content/. The searches should return the same results.

For example, searching for "MIMIC-III" using the menu bar at: https://alpha.physionet.org/ returns "MIMIC-III Clinical Database Demo" as the top hit. Searching for "MIMIC-III" using the default settings at: https://alpha.physionet.org/content/ returns "MIMIC-III Clinical Database".

**Comment by elfeto** [comment]
still happening ?
