### ISSUE TITLE
New certificate

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#572]
Prior to switching servers, we need to have a TLS certificate that is valid for:
 * physionet.org
 * www.physionet.org
 * alpha.physionet.org

(any other aliases? we can continue to point mail.physionet.org at archive and switch that one later.)

Should be possible with LE and a little hand-copying of acme challenge files.  Obviously after we make the switch the renewal should be automated.

**Comment by bemoody** [comment]
@elfeto if you have time, can you take a look at this please?

**Comment by elfeto** [comment]
The certificate has been created, I added
 - physionet.org
 -  www.physionet.org
 - mail.physionet.org
 - alpha.physionet.org
Right now they are located in the default location.
