### ISSUE TITLE
Some buttons not grayed out in project submission

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#589]
The request storage, upload files, and create folder buttons are not grayed out when the project has been submitted.

![image](https://user-images.githubusercontent.com/1282676/61131952-62b44680-a488-11e9-8789-3554e2bd8a66.png)

**Comment by elfeto** [comment]
Note, the buttons are grayed out because that is how they "normally" behave. If you had a file or folder, and click the checkbox they would become "normal buttons".

None of the buttons would work either way because the project is in submission and they would return a permission denied.
