### ISSUE TITLE
Server runs with "administrator" user account

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#593]
The django server currently runs as the user 'pn'.  This user also owns all files in pn-media and pn-static, which is fine and expected.

However, this is *also* the user account that we administrators must log into in order to deploy changes, and it's the user account who owns the git repository.  This is rather risky; it means if the django server were ever compromised, an attacker would not only be able to read/write private data, but would also be able to create backdoors for themselves, or just trash the system beyond all hope of recovery.

The UID/GID under which the django server runs shouldn't have a password or a login shell, and probably shouldn't have write permission for the git repository (/physionet/physionet-build.git) or source tree (/physionet/physionet-build).

There should be a *separate* user account that administrators use to push changes to the git repository, and to log in e.g. to run migrations.

(Note that on the old system, that separate user account is called 'pn'.  It's fine if you want to use 'pn' as the username for django on the new system, but it shouldn't be the same as the administrator account.)

**Comment by elfeto** [comment]
The Django service has to be runed by the same user that owns the all the files, or it wont allow the creation.
We can create a new user called 'uwsgi' or w/e, and switch the ownership of the django server to it, but then we would have to change the ownership of all the files. Then we could only use PN that is a regular user account as the owner of the git repo, and alter the post-receive hook script to "chown" all the files to "uwsg:www-data".
The 'pn' account here has no special privileges, and we can continue to use that to make all the changes. 
I will try it with staging to see.

**Comment by bemoody** [comment]
This was fixed with pull requests #598 and #643.
