### ISSUE TITLE
Two copies of M2WDB/matched and M3WDB/matched files

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#625]
Somehow in transferring the mimic2wdb and mimic3wdb files to the new server, we ended up with duplicated files being *copied* rather than symbolic or hard links.

Example: /data/pn-static/physiobank/database/mimic3wdb/35/3544749/3544749_0005.dat, /data/pn-static/physiobank/database/mimic3wdb/matched/p00/p000020/3544749_0005.dat, and /data/pn-static/physiobank/database/mimic2wdb/matched/s00020/3544749_0005.dat are three copies of the same file.

This is probably wasting space on the order of 2-3 TB.

**Comment by elfeto** [comment]
I just re-synchronized them.
