### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#674]
We need to be able to switch seamlessly from one web server to another, or to temporarily switch to a standby server for mainentance.

* Case 1: planned migration from one master server to another.  Everything must eventually be transferred, and public resources must be continuously available.

* Case 2: unplanned failure of master server, requiring us to send clients to a backup server.  Public resources must remain available but might be out-of-date.

If a user uploads or deletes a file through the web interface, it must not mysteriously disappear/reappear later.  Likewise if they create projects, edit descriptions, etc.

With vast resources and a lot of effort we could automatically replicate everything in multiple places and keep services continuously available.

Next best thing, I think, is to be able to stop the world:
* freeze the system on server A
* copy everything from server A to server B
* move clients over to server B
* unfreeze server B

"Freezing" means that nobody is allowed to make any changes to the filesystem or to the relational DB.  In practice, I think the easiest way to do this is to *treat all users as logged-out* (since logged-out users should never be able to make any changes anyway), and hide the 'login'/'logout'/'register' pages

(A side effect being that restricted projects would be completely unavailable.)

Questions to resolve:

1. How can we get Django to treat all users as logged-out?

2. What is the fastest way to move the relational DB from one server to another?  (Assuming that the system is frozen so we don't care about propagating changes; but we do need to have a complete and internally consistent copy, and the web server continues to access the database in the meantime.)

**Comment by bemoody** [comment]
Trying to work through this, I'm realizing that we actually should support a few different maintenance modes:

- "no-upload" mode: Everything works normally except that active projects can't be modified.

- "no-changes" mode: Visitors can log in and out (and download protected databases) but changes can't be saved (e.g. you can't create/edit projects.)

- "no-auth" mode: No ability to log in.  Protected databases are inaccessible.


From my understanding, it should be possible to make a graceful transition from one postgres server to another in a matter of seconds, which means a well executed transition should only require us to sit in "no-changes" mode for a few seconds.  But transferring active project files could take minutes or hours, during which time we want to be in "no-upload" mode to prevent loss of data.


I'm now looking at how to implement this using middleware.  It seems like it should be quite feasible.


I still need to understand how exactly this "log shipping" stuff is supposed to work.

**Comment by elfeto** [comment]
> How can we get Django to treat all users as logged-out?

We can force log them out.

>"no-changes" mode: Visitors can log in and out (and download protected databases) but changes can't be saved (e.g. you can't create/edit projects.)

I think that might also include no-auth since the login will store that information of last login.

Can you elaborate on this "log shipping"? I don't seem to understand what you mean.

**Comment by bemoody** [comment]
> We can force log them out.

I don't mean logging out, exactly.  If you "log in", and walk away
from your computer for 6 hours, and during that time the server is
switched, your browser should still be "logged in" when you return.

> I think that might also include no-auth since the login will store that
> information of last login.

Yeah, it's true that logging in will save some information to the
database.  But it's not a particularly essential piece of information.

It's the difference between "anyone who happened to log in between
1:00 and 3:00 might need to log in a second time" and "no one is able
to access any restricted/unpublished resources between 1:00 and 3:00".

> Can you elaborate on this "log shipping"? I don't seem to understand what
> you mean.

As in "how do I move from one postgres server to another with no downtime".

**Comment by bemoody** [comment]
Oh, for the love of almighty %&*@$(.

"When DEBUG is False, Django will email the users listed in the ADMINS
setting whenever your code raises an unhandled exception and results
in an internal server error (strictly speaking, for any response with
an HTTP status code of 500 or greater)."
