### ISSUE TITLE
Cert renewal

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#703]
The certificate for staging expires soonish.  Certificates for alpha/production and for archive are valid for slightly longer.

I don't want to deal with this right now but it needs to be done soon.

**Comment by elfeto** [comment]
In #740 you changed it from 443 to 80. I also added nagios checks for certificates to send email when they are near expiration date.

**Comment by bemoody** [comment]
Fixed now, I hope?  I can't figure out how "certbot renew" decides what SANs to use (maybe it parses them out of the existing certificate?!) - so I ran "certbot certonly" with the new list of domains.  The upshot of which is that I still don't know whether automatic renewal will actually work, but I hope it will.  See what happens in another two months.
