### ISSUE TITLE
Allow credentialing application to be withdrawn

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#707]
KP has asked for us to add a feature to allow a PhysioNet user to withdraw a credentialing application before it is approved/declined.

This could be implemented by adding a "Withdraw application" button on the following webpage:
http://localhost:8000/settings/credentialing/, below the following text

![Screen Shot 2019-08-26 at 16 12 28](https://user-images.githubusercontent.com/822601/63720056-51e34880-c81c-11e9-9764-209c8ba033f4.png)

**Comment by elfeto** [comment]
Fixed in #749
