### ISSUE TITLE
Checks on optional fields in credentialing form

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#709]
Some fields in the credentialing form are optional but should be
required under particular circumstances.

- (post pull #706) if reference category or name or email or title is
  supplied, then all four must be supplied.

- if country is USA or Canada then state should be required.

- possibly other things.

These should be addressed by additional checks in
CredentialingApplicationForm.clean().

**Comment by elfeto** [comment]
I fix in #787 " if reference category or name or email or title is supplied, then all four must be supplied."
The rest is fixed
