### ISSUE TITLE
URLs should only be displayed in public profiles of credentialed users

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#715]
Allowing any user to create a profile with a link to an external site is a bit risky. If we are going to support user-generated URLs in public profiles, then we need to do some kind of review of the user first. My suggestion is that URLs can only be displayed in public profiles if the user is credentialed.

**Comment by elfeto** [comment]
There are several credentialed people that have random external websites in their profile. It might be their company, but it still the home page for the website, and there are even at least one that cannot be reached. 

The same goes for un-credentialed people that most of them are the same, but one that is a link to a laptop buying site. 

Maybe doing what @alistairewj  loves, and create a dashboard like admin page, which lists all changes for the current week? 
For example:
 - UserX added a email address
 - UserY signed DUA for O database
 - UserA added a picture
 - UserL added a website to his profile

Then we can add things like Project X has an outstanding storage request there also, and more things?
