### ISSUE TITLE
Public profiles should display a list of contributed projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#716]
If a user has contributed a project to PhysioNet, then the project should be displayed on the user's public profile.

**Comment by elfeto** [comment]
Should the user be able to toggle this on and off ? assuming that the user doesn't want to show this in the profile, or we just force it for all ? (since its not a bad idea)

**Comment by elfeto** [comment]
This is currently live. I made a PR to change how its displayed.
