### ISSUE TITLE
/settings/cloud/ is uninformative

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#720]
The page /settings/cloud/ contains a form field labelled "GCP Email" and a field labelled "AWS ID".

The page explains absolutely nothing about what these fields mean, what they do, why somebody might want to complete them (or might not want to complete them), or what exactly is supposed to go in them.

**Comment by tompollard** [comment]
Funny you say that, this was bothering me earlier too. Definitely needs improvement!

**Comment by elfeto** [comment]
Happier with the description added? or still a bit uninformative ?
