### ISSUE TITLE
Hyperlinks from HTML previews are broken if project is unpublished

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#752]
If you navigate to a file and then click it to open the HTML preview, there is a hyperlink bar at the top:

```[PREVIEW]: Project Name
File: <base> / test1 / filename.txt (10 bytes)
```

The folders are links, but they are broken when the project is unpublished. In my BERT-deid project the `test1` link points to https://physionet.org/projects/eVT6feluFB2RPWmd6JbF/files/test1#files-panel which then an raises nginx 404. The links work on published projects though (I tested a few). Also seems to not work regardless of the type of file previewed.

Oddly enough the folder navigation bar in the file panel works fine (`test1` links to https://physionet.org/projects/eVT6feluFB2RPWmd6JbF/#files-panel ), it's only when you load a preview that it breaks.

**Comment by bemoody** [comment]
Buggy generation of the breadcrumbs, but also buggy redirection...

https://physionet.org/projects/eVT6feluFB2RPWmd6JbF/files/test1

in principle, ought to redirect to

https://physionet.org/projects/eVT6feluFB2RPWmd6JbF/files/test1/

not to

https://physionet.org/protected/active-projects/eVT6feluFB2RPWmd6JbF/test1/

**Comment by alistairewj** [comment]
I just tested this on production with one of my projects and the fix seems to work.
