### ISSUE TITLE
Add "Remind author" email for projects that are awaiting revisions

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#772]
Projects are getting stuck in the "Awaiting Author Revisions" stage. To help move these projects along, a good first step would be to add a "reminder" email.

We could add a "Remind author" and "Last reminded" column to the table in the "Awaiting Author Revisions" tab at: https://physionet.org/console/submitted-projects/, along with a button to send a reminder email. The "Last reminded" column should be populated with the most recent date. 

This is a first step towards slightly more sophisticated functionality for handling projects that are awaiting revisions. At some point we probably want to be able to archive a project that has been sitting for too long.

**Comment by elfeto** [comment]
Would the same be helpful backwards ? If the author is waiting for X time for the "Awaiting Decision", then send an email as a reminder? 

Also, how long until emails can be sent?  1 day? 2 days ?

**Comment by tompollard** [comment]
Thanks for the pull request - sorry, missed these questions.

> If the author is waiting for X time for the "Awaiting Decision", then send an email as a reminder?

Think I'd prefer not to do this initially, but if you've included it in your pull request then we can give it a try and see how it goes.

> Also, how long until emails can be sent? 1 day? 2 days ?

A week maybe?

**Comment by elfeto** [comment]
So, I only included editor reminding the authors.

Then the wait time between emails right now is set for 1 day. But the editor is the person that can click the button. I can set it for a week if you want to...

**Comment by tompollard** [comment]
> Then the wait time between emails right now is set for 1 day. But the editor is the person that can click the button. I can set it for a week if you want to...

As it's the editor, 1 day sounds good to me.
