### ISSUE TITLE
Add "Active Users" item to the Console?

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#776]
Usually when searching for a user, we are interested in active users. The "All Users" list is getting pretty noisy, so for now (until we do something about this), it might be helpful to add a new "Active Users" item to the list, which displays all of the users that are not in "Inactive Users". The "All users" item could be moved to the bottom of the list.

![Screen Shot 2019-10-09 at 14 40 02](https://user-images.githubusercontent.com/822601/66510460-15556e80-eaa3-11e9-9b66-43ce1eeec067.png)

**Comment by elfeto** [comment]
I would be fine with this assuming we leave the definition of "Inactive Users" as is. The current definition of inactive users is:
 - Accounts that have NOT been activated
 - Accounts that have NOT been logged in the last 90 days

**Comment by bemoody** [comment]
Done; see pull request #805.
