### ISSUE TITLE
Validation on project title field is too strict

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#811]
The form validation for the title field for projects does not allow some common characters, including question marks and commas ("Letters, numbers, spaces, underscores, and hyphens only. Must begin with a letter or number.")

The validation should be made less strict. As a start, we should probably allow:
- question mark `?`
- comma `,`
- colon `:`

See also #714

**Comment by bemoody** [comment]
See also #515 :)

In project titles, I'd actually prefer to see Unicode apostrophes and
dashes (and quotes, if those are allowed) in place of ASCII
punctuation.  In some contexts we might need to convert the title into
ASCII, but in HTML we should use the pretty form.

**Comment by tompollard** [comment]
Fixed in https://github.com/MIT-LCP/physionet-build/pull/816
