### ISSUE TITLE
Add linked papers and code to the challenge summary page

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#819]
Request from Matt:

> First, I noticed that the new website doesn’t list the numbers of papers and algorithms for each Challenge or provide links to the papers and submissions:
Old website: https://archive.physionet.org/challenge/
New website: https://physionet.org/about/challenge/

> Unless there was a good reason to remove these numbers and links, could we add them again? They’re helpful for showing the level of engagement and for making the papers and algorithms more accessible.

**Comment by tompollard** [comment]
@elfeto please could you put this somewhere near the top of your priority list? (cc @bemoody in case you would like to chat about this).

**Comment by elfeto** [comment]
@tompollard  I can work something with this, but this will be contradictory to the PR #770  that I believe you wanted. 

In the old website, the papers and the algorithms are in a folder of the challenge. 
I can't think of another way to add those two things than the way of the old site. But if we do it like that, then I would assume it will require a new version every time we we add a paper or algorithm, no ?

**Comment by tompollard** [comment]
Yep, good point to raise. I'd like to be able to merge #770, but it definitely needs a softer approach than just getting rid of the static pages and pushing everyone to search (particularly for the challenges). Lucas is aware of this (we discussed the PR a week or two ago), so it's fine to go ahead with this even though it overlaps. 

> But if we do it like that, then I would assume it will require a new version every time we we add a paper or algorithm, no ? In the old website, the papers and the algorithms are in a folder of the challenge. I can't think of another way to add those two things than the way of the old site. 

Putting the papers into a folder in the challenge files section sounds good to me (I think that some already have this?). 

It is true that updating content means bumping the version, but I don't think it should be a problem. We'll do our best to make sure that papers and algorithms are released in bundles. For the past/migrated challenges, I'd just go ahead and add the content if needed without updating versions.
