### ISSUE TITLE
New validation rules do not allow title to begin with a number

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#850]
It looks like the validation rules added in https://github.com/MIT-LCP/physionet-build/pull/832 do not allow a project title to begin with a number. Is this intentional?

![Screen Shot 2020-01-13 at 16 23 21](https://user-images.githubusercontent.com/822601/72293399-72703b80-3621-11ea-9111-c2b7f30da8ad.png)

There are existing projects that begin with a number (e.g. https://physionet.org/content/bhi-2018-challenge/), so I would prefer to stick with the original behaviour if possible.

If we do decide to prevent titles that begin with a number, this rule should be made clear in the error text.

**Comment by elfeto** [comment]
validate_title was kept mostly the same. The rule before and after #832 was set to only accept alphabetical starts.

This was added on #816

**Comment by tompollard** [comment]
Thanks for investigating. In this case I guess we just need to decide whether we: 

1. continue to prevent numbers at the start of titles, and if so explain this in the error 
2. allow titles to begin with a number.

My preference is 2, unless anyone can think of a reason why this is a bad idea!
