### ISSUE TITLE
Sequence of authors in Google Datasets is incorrect

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#862]
The order of authors in [Google Datasets](https://datasetsearch.research.google.com/) does not match the order of authors on PhysioNet. For example, the Paediatric Intensive Care Database:

- PhysioNet: https://physionet.org/content/picdb/1.0.0/ ("Haomin Li,  Xian Zeng,  Gang Yu ") 
- Google Datasets: https://datasetsearch.research.google.com/search?query=Paediatric%20Intensive%20Care%20database&docid=UFHDv91BXka2GDENAAAAAA%3D%3D ("Gang Yu; Haomin Li; Xian Zeng")

The sequence is important to get right, so this should be fixed. Google Datasets uses the schema.org markup embedded in the project page, which in this case is:

```json
<!-- https://schema.org/ metadata for discovery -->
<script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "name": "Paediatric Intensive Care database",
  "description": "The Paediatric Intensive Care (PIC) database is a large paediatric\u002Dspecific, single\u002Dcenter, bilingual database comprising information relating to children admitted to critical care units at a large children\u0026rsquo\u003Bs hospital in China. The database is de\u002Didentified and includes vital sign measurements, medications, laboratory measurements, fluid balance recordings, diagnostic codes, demographic information, and more. The data are publicly available after\u0026nbsp\u003Bcredentialing, which includes completion of a training course on research with human subjects and signing of a data use agreement mandating responsible handling of the data and adherence to the principle of collaborative research. The PIC database builds upon the success\u0026nbsp\u003Bof the\u0026nbsp\u003Bwidely used MIMIC (Medical Information Mart for Intensive Care) database, and extends the approach into the field of paediatric critical care. The database has many unique\u0026nbsp\u003Bcharacteristics which\u0026nbsp\u003Bsupport academic and industrial research including the development of\u0026nbsp\u003Bmachine learning algorithms, clinical decision support tools, quality improvement initiatives, and international data sharing.",
  "version": "1.0.0",
  "license": "https://github.com/MIT\u002DLCP/license\u002Dand\u002Ddua/tree/master/drafts",
  "datePublished" : "Dec. 1, 2019",
  "url": "https://physionet.org/content/picdb/1.0.0/",
  
  "identifier": "https://doi.org/10.13026/bcbd\u002D4t11",
  
  "creator": [
  
    {
      "@type": "Person",
      "givenName": "Haomin",
      "familyName": "Li",
      "name": "Haomin Li"
    },
  
    {
      "@type": "Person",
      "givenName": "Xian",
      "familyName": "Zeng",
      "name": "Xian Zeng"
    },
  
    {
      "@type": "Person",
      "givenName": "Gang",
      "familyName": "Yu",
      "name": "Gang Yu"
    }
  
    ],
  "includedInDataCatalog":{
     "@type": "DataCatalog",
     "name": "physionet.org"
  },
  "distribution": [
    {
      "@type": "DataDownload",
      "contentUrl": "https://physionet.org/content/picdb/1.0.0/#files"
    }
  ]
}
</script>
```

Documentation on Google Datasets is at: https://developers.google.com/search/docs/data-types/dataset#citations-and-publications. See also #147

**Comment by bemoody** [comment]
It looks like we *are* listing the authors in the correct order and
Google is screwing them up somehow.  What gives?

**Comment by tompollard** [comment]
Exactly, not sure! It's possible there is a way of specifying the sequence in the metadata, though I don't see anything obvious.

**Comment by bemoody** [comment]
Looking at another random entry from the search above:

https://figshare.com/articles/Baseline_characteristics_of_children_admitted_to_the_paediatric_intensive_care_unit_PICU_with_severe_acute_respiratory_tract_infections_SARIs_or_medium_care_MC_with_acute_respiratory_tract_infections_ARTIs_associated_with_a_single_virus_infection_in_the_a/3109075/1

* Authors listed by Figshare:

(1) Fleur M. Moesker
(2) Jeroen J. A. van Kampen
(3) Annemarie M. C. van Rossum
(4) Matthijs de Hoog
(5) Marion P. G. Koopmans
(6) Albert D. M. E. Osterhaus
(7) Pieter L. A. Fraaij

* Authors listed by Google Dataset Search:

(3) Annemarie M. C. van Rossum
(4) Matthijs de Hoog
(7) Pieter L. A. Fraaij
(2) Jeroen J. A. van Kampen
(5) Marion P. G. Koopmans
(6) Albert D. M. E. Osterhaus
(1) Fleur M. Moesker

It's possible we missed something in the schema.org docs but this
looks to me like a bug on Google's end.

**Comment by tompollard** [comment]
> It's possible we missed something in the schema.org docs but this looks to me like a bug on Google's end.

Good idea to check Figshare. The sequence seems to change on Google Datasets. At one point I was promoted to lead author for the [Women in Data Science challenge](https://datasetsearch.research.google.com/search?query=women%20in%20data%20science&docid=RqCg%2FHJgn7wlRM6SAAAAAA%3D%3D) (which motivated me to raise this issue!) but the order is now different .

**Comment by tompollard** [comment]
Update from Google Datasets:

> we are aware of the bug and are working on figuring it out.

**Comment by tompollard** [comment]
It looks like the bug was fixed with Google Datasets. It now reports the correct order for authors.
