### ISSUE TITLE
Add option to provide ORCID in user profile

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#870]
It should be possible for users to provide their [ORCID](https://orcid.org/) (unique researcher ID) in the user profile. This may be useful for several reasons (e.g. syncing projects with research profiles; identifying duplicate accounts; enabling login with ORCID credentials; providing additional information for credentialing applications, etc). More thought is needed about details of the implementation.

**Comment by tompollard** [comment]
This may help with handling credentialing applications, so it would be good to prioritize. Details on the APIs are at: https://orcid.org/organizations/integrators

**Comment by elfeto** [comment]
After checking the API, I found https://orcid.org/about/membership while requesting access to it https://orcid.org/content/register-client-application-0. I Either way requested a client application that has to be approved by them and I will get more information about it.

BUT it seems to be a paid service. I would recommend to see if MIT has some kind of connection with ORCID and see if there is a possibility to talk with a person that can give us more information.

The other option right now would be to just add an input box to ask for the individual orchid, but there is no way to corroborate that the ID added is actually the person's ID.

**Comment by tompollard** [comment]
> BUT it seems to be a paid service. I would recommend to see if MIT has some kind of connection with ORCID and see if there is a possibility to talk with a person that can give us more information.

Great suggestion, let's contact MIT Libraries as a starting point [UPDATE: I checked a little while ago and it looked like there is a free service that does what we need it to do].
