### ISSUE TITLE
CopyeditForm NullBooleanField clean is broken

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#877]
The form clean doesn't work that well. 

There are three options:
YES_NO = (
    ('', '-----------'),
    (1, 'Yes'),
    (0, 'No')
)

For the form '' and 0 are the same and will be treated as a False.

**Comment by bemoody** [comment]
What's the problem exactly?

I assume you're talking about 'made_changes' in CopyeditLog.  It's
null when the object is initially created and should then be set to
true or false by the editor.

The third choice, AFAIK, is simply there to ensure that the browser
stops you from submitting the form if you haven't selected either
"yes" or "no".

**Comment by elfeto** [comment]
You can submit the form without selecting yes or no. Just leave ----------- in the select, and click submit it will work.

**Comment by bemoody** [comment]
The <select> should have the "required" attribute.  Does it?

Might be worth adding server side validation but would be much better
to (also) fix it on client side if we can.
