### ISSUE TITLE
Move nginx temporary files off root filesystem

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#919]
So long as we allow 10 GB POSTs (!), we shouldn't be storing them on the root filesystem.  We don't have space for that!

Sounds like "client_body_temp_path" might be what we want, I'm not sure.

It'd be better if we could set a size limit on a per-URL basis, and even better if we could check *before uploading* whether the upload will exceed the given project's quota :/

**Comment by elfeto** [comment]
>It'd be better if we could set a size limit on a per-URL basis, and even better if we could check before uploading whether the upload will exceed the given project's quota :/

I think the only way to do that would be using JS. 
For example, you can get the size in bytes. (I don't know how unreliable this would be tho)
https://www.codexworld.com/how-to/get-file-info-name-size-type-javascript/

**Comment by bemoody** [comment]
Not a bad idea; it's not foolproof but could certainly save people a
bit of annoyance.  Assuming it works, which I haven't tested :)
