### ISSUE TITLE
Allow handling editor to be reassigned

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#943]
It should be possible to reassign a project to a different handling editor. i.e. if admin1 becomes handling editor for a project, they should be able to make admin2 handling editor instead. This is useful if someone needs help with handling a project, goes on vacation, moves to a new role, etc.

**Comment by elfeto** [comment]
There are two options to do this:
Option 1. Add a button in the Editor home page, that will open a pop up window similar to the screenshots:
<img width="1505" alt="Screen Shot 2020-03-30 at 1 32 24 PM" src="https://user-images.githubusercontent.com/3857286/77948373-ef0ecf80-728a-11ea-931a-efa469ad3d6c.png">
<img width="488" alt="Screen Shot 2020-03-30 at 1 31 47 PM" src="https://user-images.githubusercontent.com/3857286/77948370-ee763900-728a-11ea-8d66-06f413bb0913.png">

Option 2. Add a tab in the project info page with the same information of the modal above.
<img width="1182" alt="Screen Shot 2020-03-30 at 1 33 05 PM" src="https://user-images.githubusercontent.com/3857286/77948443-06e65380-728b-11ea-87ba-65c83166b12b.png">

Note. The text on the modal is NOT updated, and will be changed with an explanation of what is happening. I took the screenshot of the Assign editor section.

**Comment by elfeto** [comment]
Both options would be permanent. Not for a specific section. You are actually dumping your work onto another person.

**Comment by tompollard** [comment]
Thanks Felipe! For me option 1 suggests that the assignment applies just for that section, so my preference is option 2.
