### ISSUE TITLE
Sorting order of applications on KP's credentialing management page

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#955]
@kpierceHST has asked for the order of applications to be updated on his page for managing applications for credentialed access (https://physionet.org/console/complete-credential-applications/).

> currently the queue is sorted first by whether or not reference has been contacted, then by date of application.  Perhaps we could insert a third criterion...

> So the three categories appearing would be:

> - reference known but not contacted
> - reference not known and not contacted
> - reference contacted about the application in question

> with each category then sorted by date of current application.

**Comment by elfeto** [comment]
This would be for example 
1. May 1, 2019 reference known but not contacted
2. May 1, 2019 reference not known and not contacted
3. May 2, 2019 reference not known and not contacted
4. May 3, 2019 reference known but not contacted
5. May 3, 2019 reference known but not contacted
6. May 2, 2019 reference not known and not contacted

or?

**Comment by kpierceHST** [comment]
No, something other:

> 1. May 1, 2019 reference known but not contacted
> 4. May 3, 2019 reference known but not contacted
> 5. May 3, 2019 reference known but not contacted
> 2. May 1, 2019 reference not known and not contacted
> 3. May 2, 2019 reference not known and not contacted
> 6. May 2, 2019 reference not known and not contacted

Anyone whose reference is known should bubble above anyone whose reference is unknown.  That will allow me to take care of the easy applications first, and let the more troublesome ones wait a bit.

Thanks!

Ken

**Comment by elfeto** [comment]
Would doing that order and changing the color from black to red would be a good idea, or keep the same black color ?
for example: 
<img width="255" alt="1" src="https://user-images.githubusercontent.com/3857286/77939900-748b8300-727d-11ea-8fa3-943b1bbdb774.png">
<img width="1570" alt="2" src="https://user-images.githubusercontent.com/3857286/77939905-75bcb000-727d-11ea-9f2a-d291beae05e3.png">

This does not has to be exclusive, we can add the red in only one or none if you like.

**Comment by kpierceHST** [comment]
I'd prefer that you keep it black.
Thanks,
Ken
