### ISSUE TITLE
Self managed credentialing outstanding task

### ISSUE THREAD

**Issue by elfeto** [MIT-LCP/physionet-build#962]
Right now is not obvious that a person has to grant access to their project. There should be a count or notification on the user's home page saying that there is an outstanding task or something.

**Comment by bemoody** [comment]
There should be one.  I just tried:

- log in as rgmark
- request access at /request-access/demoselfmanaged/1.0.0/
- log out
- log in as george
- notification is displayed in /projects/ under "Outstanding Tasks"

Is that what you're looking for, or something else?

**Comment by elfeto** [comment]
You are right. That is what I was looking for. For some reason I didn't scrolled up enough to see that.
My bad.... :(
