### ISSUE TITLE
Add and improve heading styles for project descriptions

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#975]
Currently the text editor for project descriptions lists a single header "Heading 3":

![Screen Shot 2020-03-27 at 13 21 49](https://user-images.githubusercontent.com/822601/77782807-3a787200-702e-11ea-9c93-6f0cf2174a5e.png)

The style of "Heading 3" appears almost identical to the section header (which has an `<h2>` tag). e.g. in the example below, "Methods" is the section header and "Data Acquisition" is Heading 3.

![Screen Shot 2020-03-27 at 13 21 54](https://user-images.githubusercontent.com/822601/77783114-abb82500-702e-11ea-9cb0-56cf715e82de.png)

We should improve this at some point. Regardless of the HTML tags that are used in the document, we may want to consider section headers (e.g. in this case Abstract, Introduction, Methods) to be `Heading 1`, and then we should support at least `Heading 2` and `Heading 3` and `Heading 4`.

**Comment by bemoody** [comment]
If you change format_tags to 'p;h3;h4;h5' then it will show "Heading
3", "Heading 4", "Heading 5".  This is implemented by the "format"
plugin and it doesn't look like there's a way to change the labels or
add custom options.

**Comment by bemoody** [comment]
> This is implemented by the "format" plugin and it doesn't look
> like there's a way to change the labels or add custom options.

Weirdly enough, however, it is possible to change what *tags* it uses
(config.format_h1 etc.) so in theory we could have the "h1" option
actually generate an h3 tag.

**Comment by tompollard** [comment]
> Weirdly enough, however, it is possible to change what *tags* it uses (config.format_h1 etc.) so in theory we could have the "h1" option actually generate an h3 tag.

Thanks for looking into this. Something like that would work. Kind of strange for us, but clear to the user. For reference, https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0216636 formats the article title as h1 (with id="artTitle"), then section headers as h2, subsection headers as h3 etc.

**Comment by tompollard** [comment]
I think it might be worth reopening this. We have added support for additional headers (h2, h3 etc), but the issue of h2 and h3 headers looking very similar is still there:

![Screen Shot 2021-03-22 at 13 18 55](https://user-images.githubusercontent.com/822601/112031150-629b9380-8b11-11eb-96ee-a7adf1fffa93.png)

(the HTML for this chunk is:

```
<h2 id="description">Data Description</h2>
<h3>Overview</h3>
```

It would be good to find a nice set of CSS styles to better differentiate between headers (h1 to h5).

**Comment by Lucas-Mc** [comment]
Here's some fonts if you wanna have a play around: https://www.cssfontstack.com. It might be tough though since some of the header sizes are very close to each other:
```
h1 = 2em/32px
h2 = 1.5em/24px
h3 = 1.17em/18.72px
h4 = 1em/16px
h5 = 0.83em/13.28px
h6 = 0.67em/10.72px
```
