### ISSUE TITLE
Duplicated code for authors in UnpublishedProject

### ISSUE THREAD

**Issue by Lucas-Mc** [MIT-LCP/physionet-build#984]
See lines 718 and 723. This may ultimately require a migration since it is part of the models but hopefully not! Still needs to be tested to be absolutely sure though.
https://github.com/MIT-LCP/physionet-build/blob/0301cfa6fd13d0a4c66f716a7b965e51a5111a82/physionet-django/project/models.py#L718-L723

**Comment by tompollard** [comment]
Thanks Lucas, well spotted. @shulim would you like to pick this one up? 

"Migrations" are files that are run by Django to implement a database change. Classes in models.py map to tables in the Django database, and class attributes map to columns in the tables.

In this case, "authors" is defined twice, unnecessarily. Hopefully this means that we haven't ended up creating duplicate columns in our database. It shouldn't do, but it would be worth double checking to be sure! To check, delete the duplicate row and then run:

```python manage.py makemigrations```

If you see "No changes detected", then a migration is not required.
